pages/data.html

I do not actually see any datasets on the DIRT page (Iyer-Pascuzzi and Bucksch papers), so I wonder if there could be a newer (iPlant?) link for that one.

Datasets table: Add a link to Bellwether paper, fix a link

---

pages/documentation/function_docs/vis_tutorial.md

Fix for Figure 8 in [vis_tutorial](http://plantcv.danforthcenter.org/pages/documentation/function_docs/vis_tutorial.html).
Final wmasked (19) vs. black-white after filling.

Image 19 thumbnail should link to image 19, not 18 (one line fix)

---

README.md

These are small stylistic changes. You can preview the result  via my current fork: https://github.com/jshoyer/plantcv/blob/dev/README.md
I think we should go aheand and close #80 now, even if you do not want to merge these changes.
Consider cherrypicking these and/or related commits to update the `master` branch readme, which is more important than the `dev` branch one.

Tighten up top-level ReadMe file to address #80

---

docs/vis_tutorial.md
plantcv/analyze_object.py
plantcv/roi_objects.py

No changes to code, just comments.
You may wish to defer merging the two lines edited in analyze_objects. It may be better to just remove the 'imgname' argument. I did not go ahead and do that, because I do not know how many scripts that might break.
See also issue #121.

Typo fixes in docstrings etc.

---

docs/faq.md
docs/index.md
mkdocs.yml

This is a proposed new documentation page designed to help users in a hurry and preempt questions. There are no changes to code.
I have not tested the new page with `mkdocs build`, so I am not 100% sure that it will render properly.
I would add a 'documentation' label to this, but I do not see the menu alluded to in the PR template.
Let me know if I can make changes, file related issues etc.
- (NA) Relevant tests (and test data) have been added or updated and passed.
- (NA) Relevant issues were updated or added.

A quick start on an FAQ page

---

docs/read_image.md
plantcv/readimage.py
tests/tests.py

This commit adds an input parameter to `readimage`, but it has a
default value so it will not break the existing API. The main purpose
is to add the ability to automatically plot input images in Jupyter.
A debug option was added to `readimage` so that the input image can be automatically plotted in Jupyter notebooks. Because debug=None is the default, this change will not break existing usage of readimage without the debug option set. The unit test and documentation page were updated accordingly.
New minor feature.

Added debug to readimage

---

docs/nir_tutorial.md
docs/sobel_filter.md

The sobel filter specifies that "scale" is a parameter, when it is not.
Remove the line conerning "scale"
"dx" and "dy" specify that the derivative can be 1 to 3
Change the documentation to specify the derivative can be from 0 to 3
This is as according to the example usage on the sobel filter documentation.

Fix documentation for Sobel Filter

---

docs/nir_tutorial.md

The rectangle_mask function returns 5 variables.
Fix NIR tutorial documentation to show that

Change NIR pipeline tutorial documentation

---

docs/nir_tutorial.md

I cannot find border_mask() in the documentation.
Also, running some code with border_mask() creates this error:
AttributeError: 'module' object has no attribute 'border_mask'
Change border_mask() to rectangle_mask() in NIR tutorial documentation.

Change NIR documentation

---

plantcv/crop_position_mask.py
plantcv/resize.py
requirements.txt
tests/tests.py

This pull request primarily fixes a bug in the function crop_position_mask where the mask image that is returned by the function is destroyed by a call to cv2.findContours in debug mode only (in normal mode, findContours is not used). A new test was added for the resize function as well.
Bug fix

Bug fix resize and crop position

---

.travis.yml
plantcv/learn/naive_bayes.py

The naive_bayes_multiclass training method now skips cells in the RGB pixel sample table that don't contain any data.
Bug fix

Fixes bug where missing RGB data causes plantcv-train.py to crash

---

plantcv/analyze_NIR_intensity.py
plantcv/analyze_color.py
plantcv/fluor_fvfm.py
plantcv/learn/naive_bayes.py
plantcv/plot_colorbar.py
plantcv/plot_hist.py
plantcv/triangle_auto_threshold.py
tests/tests.py

Addresses issue #223. Quiets matplotlib warnings when attempting to change the plotting backend more than once in the same scope.
Annoyance fix.

Disabled warnings for matplotlib.use

---

docs/multi-plant_tutorial.md
docs/vis_tutorial.md

Issue #257 describes an incorrect portion of the tutorial. Updated docs to match changes that had been made to cluster_contours function.
Issue #255 described errors in documentation for the VIS tutorial. Removed extra parameter from pcv.analyze_color function and removed the line ab_cnt = pcv.logical_or(maskeda_thresh1) since it was missing an argument and wasn't used downstream in the tutorial.
- [NA] Relevant tests (and test data) have been added or updated and passed.

tutorial_docs_correction

---

plantcv/plantcv/analyze_bound_horizontal.py
plantcv/plantcv/analyze_bound_vertical.py
plantcv/plantcv/analyze_color.py
plantcv/plantcv/analyze_nir_intensity.py
plantcv/plantcv/analyze_object.py
plantcv/plantcv/cluster_contour_splitimg.py
plantcv/plantcv/fluor_fvfm.py
plantcv/plantcv/report_size_marker_area.py
plantcv/plantcv/watershed.py

changed method to remove file extensions from file names from string slicing to `os.path.splitext()` to accurately handle different length extensions
addresses:
https://github.com/danforthcenter/plantcv/issues/277
https://github.com/danforthcenter/plantcv/issues/279#issue-386409066

changed method for removing file extensions

---

docs/fluor_fvfm.md
docs/psII_tutorial.md
docs/updating.md
plantcv/plantcv/fluor_fvfm.py
plantcv/plantcv/plot_colorbar.py
tests/tests.py

The PSII camera in the LemnaTec system at the Danforth Center outputs 16-bit images so the Fv/Fm analysis function checked that the input images were 16-bit. However, the functionality of the module does not rely on the images being 16-bit, so I removed this check so that 8-bit images could be used. I also updated the pseudocolored image plotting code and documentation.
See issue #285 
Updates existing function to use 8-bit images in addition to 16-bit images.

Update the Fv/Fm function to allow 8- or 16-bit images

---

plantcv/plantcv/plot_image.py

Looks like applying the Agg backend in the plot_image function disables displaying images in Jupyter because the Agg backed is a non-GUI backend.
Removed the matplotlib Agg backed in the `pcv.plot_image` function. Using Agg disables image display in Jupyter because it's a non-GUI backend.
Bug fix.

Remove Agg backend in plot

---

docs/updating.md
docs/visualize_histogram.md
plantcv/plantcv/__init__.py
plantcv/plantcv/visualize/colorize_masks.py
plantcv/plantcv/visualize/histogram.py
tests/tests.py

- I had written colorize_masks to take either a list of strings (from the dictionary of potential colors) or a list of tuples, so users could specify their own colors. But now they can list either type of color.
- Allow users to pick the color of the line plot in their histogram and give them the option to title the histogram plot as well. Update testing to cover new if statement.

Visualize functions options 

---

plantcv/plantcv/analyze_nir_intensity.py

Updated the analyze_nir_intensity function to use cv2.calcHist instead of np.histogram. calcHist lets you use a mask, which excludes all the background pixels. This allows us to use the normal range of 0-256 (or similar) and makes the output correctly in that range. The bin values were also adjusted to respond to the user input bin number.
Closes #386 
Fixes small bug in `plantcv.analyze_nir_intensity`, makes the output histogram data cleaner.

Use OpenCV calcHist method

---

plantcv/plantcv/print_image.py
tests/tests.py

Removes extraneous matplotlib dpi setting when writing an array to file with `cv2.imwrite()`
closes #406

removed matplotlib dpi when using cv2.imwrite

---

plantcv/plantcv/visualize/pseudocolor.py

In the pseudocolor function the mask needs to be inverted, this pull request restores the previous functionality. Scaling (using vmin and vmax) of the background image is removed.
Bug fix.

Restore pseudocolor mask functionality

---

docs/closing.md
docs/get_kernel.md
docs/opening.md
environment.yml
mkdocs.yml
plantcv/plantcv/__init__.py
plantcv/plantcv/get_kernel.py
requirements.txt
tests/tests.py

Allow scikit-image to use best available version
We currently restrict scikit-image to use version <0.15. This can create an issue on Windows reported in #428 where v0.14.3 is installed but is not working on Windows (https://github.com/pyxem/pyxem/issues/422).
This pull request updates the version limitation in `requirements.txt` to limit the scikit-image version.
Added new function to create structuring elements more easily (`pcv.get_kernel`). Also add example of defining a custom kernel in the documentation. Closes #427 
Bug fix (Windows)

Remove version restriction

---

docs/multi-plant_tutorial.md
docs/roi_multi.md
plantcv/plantcv/analyze_color.py
plantcv/plantcv/cluster_contours.py
plantcv/plantcv/roi_objects.py
plantcv/plantcv/transform/color_correction.py
tests/tests.py

* Realized the limitations of the current method for filtering out objects that don't partially overlap with a region of interest (details discussed in #435 ) so updated the method to be more robust (and generally more efficient). 
* While comparing the results from `pcv.roi_objects` it became clear that there were small (10's of pixels) differences, usually in gaps, that we believe resulted from using `cv2.drawContours` despite trying to use the most exact parameters in `cv2.findContours`. Rather than re-plotting contours that get kept, we create a mask and only delete contours that are filtered out. 
* Update unit tests to reflect the more accurate method within the `pcv.roi_objects` function. 
* Closes #435 
* Update row and column parsing in `pcv.cluster_contours` to handle numbers …

Enhance pcv.roi_objects

---

plantcv/parallel/parsers.py
plantcv/plantcv/analyze_color.py

Python dateutil does not like parsing datetimes in the format Y-M-D H-M-S. But removing the hyphens to either YMD HMS or YMDHMS works. This pull request updates the datetime parser in the parallel subpackage to remove "-" characters from datetime strings prior to parsing.
Is this a bug fix
Possibly fixes #444 and somewhat addresses #423

Remove hyphens in datetime

---

environment.yml
requirements.txt

Prevent using NumPy 1.17+
From initial testing it looks like NumPy 1.17 changes the way NumPy data saved to files (NPY or NPZ files) are read for security reasons. We have a fair amount of NPZ files in our test dataset, so this causes the tests that use these data to fail. This pull request pins NumPy to versions < 1.17 for now until we address #447.
Is this a modification to our dependency list.
Issue #447 tracks what we need to do to use NumPy 1.17+.

Restrict max NumPy version

---

plantcv/plantcv/hyperspectral/__init__.py
plantcv/plantcv/hyperspectral/extract_index.py
tests/tests.py

* Add a function to the hyperspectral package that will extra spectral indices from hyperspectral datacubes. The function allows for some wiggle room to allow for hyperspectral data that doesn't exactly match the wavelength needed to calculate an index since neighbor bands tend to be highly correlated with one another. The amount of wiggle room is flexible; it can be refined using the `fudge_factor` parameter (rename??). For now the user needs to input the specific index that is desired but we may later update so that a list of indices can get returned at the same time, or maybe all similar indices will be returned. 
* Includes unit testing for the new function. 
* New feature 
#443 
#203

Extract spectral indices

---

vice/Dockerfile

Adds a second Dockerfile for building a container for use in the CyVerse VICE interface (https://learning.cyverse.org/projects/vice/en/latest/developer_guide/adding.html). After the Dockerfile is in place, we will set up a second automatic Docker build in DockerHub.
Once the container is available we will try creating a CyVerse app in the Discovery Environment that can use VICE so a user can use PlantCV in Jupyter within CyVerse.

Add Dockerfile

---

plantcv/parallel/process_results.py

This pull request updates the `plantcv.parallel.process_results` method to remove the use of the `keys` method that was used to iterate over the keys of two dictionaries. `keys` will return an error if the dictionary is undefined, which occurs when the metadata dictionary is missing in some instances as described in #466. Instead `process_results` is updated to use a for loop on the dictionary without `keys`, which functions in the same way but does not require the dictionary to be defined and just skips the loop if it is not.
Is this a bug fix
Should fix #466

Update process_results to bypass missing metadata bug

---

environment.yml

Updated environment.yml to have defaults channel above conda-forge to be similar to resolution in #469 
the same problem (I think) as #469 just bit me when I was trying to install `add-regex-metadata-parser` branch into my `test-environment`

add defaults channel for dependencies when installing from source

---

plantcv-utils.py
plantcv/utils/sample_images.py

Coerce 'num' argument in run_sample_images to integer to avoid `TypeError: '>' not supported between instances of 'str' and 'int'`
If i run sample_samples without an n argument it works fine. I could not figure out why or at what point num is getting converted to a str but that's what the error suggests. I tested the function with `num = int(num)` and it works for me.
```
(plantcv) C:\Users\dominikschneider\Documents\phenomics\GoldStandard2>python %CONDA_PREFIX%/Scripts/plantcv-utils.py sample_images -s data/raw_snapshots/vis -o data/testimages/vis -n 50
Traceback (most recent call last):
File "C:\Users\dominikschneider\Miniconda3\envs\plantcv/Scripts/plantcv-utils.py", line 74, in <module>
main()
File "C:\Users\dominikschneider\Miniconda3\envs\plantcv/Scripts/pla …
```

Sample images fix

---

plantcv/plantcv/__init__.py
plantcv/plantcv/hyperspectral/analyze_spectral.py
plantcv/plantcv/hyperspectral/extract_index.py
plantcv/plantcv/hyperspectral/read_data.py
plantcv/plantcv/readimage.py
tests/hyperspectral_data/darkReference2.hdr
tests/tests.py

Added a `Spectral_data` class to the hyperspectral sub-package in order to streamline inputs to functions. Attach all the important metadata from the header dictionary that is created while reading in ENVI data as properties of the spectral data object as the image is read in. 
* Enhancement
#203 
The instances of this class have a lot of properties since there is a lot of metadata about a hyperspectral datacube that is important to analysis functions used on it. We plan to do a similar transition to the rest of the PlantCV functions. This should remove the need for repetitive inputs (e.g. contours and hierarchies) since we can make them attributes for objects of an image array data class.

Add Spectral_data class  

---

docs/pipeline_parallel.md
plantcv-workflow.py
plantcv/parallel/__init__.py
plantcv/parallel/parsers.py
plantcv/utils/converters.py
tests/tests.py

Added a new argument to plantcv-workflow so the user can specify the timestamp format with --timestampformat or -s
I made the argument  mandatory with adaptor=filename and optional with phenofront. the Default value is %Y-%m-%d %H:%M%S.%f which I am guessing is the preexisting standard at the Danforth when using phenofront format.
This both a bugfix #473  and new feature to complement regex metadata parsing feature #454 . 
Closes #473 
I also fixed test for checking date_range since it was passing for the wrong reasons. I exported check_date_range to namespace so I could write a direct test. going through metadata_parser seemed heavy handed.   
We could potentially rewrite the other check_date_range …

add timestamp format argument to plantcv-workflow

---

plantcv-workflow.py

The help description text for the new `timestampformat` option has "%" characters that are used as placeholders by `argparse`. They need to be escaped using "%%" otherwise `argparse` throws an error when the help menu is printed. 
Bug fix
Solution: https://stackoverflow.com/questions/20480018/valueerror-unsupported-format-character

Fix plantcv-workflow help function

---

plantcv/plantcv/hyperspectral/extract_index.py
plantcv/plantcv/hyperspectral/extract_wavelength.py
tests/tests.py

The function `plantcv.plantcv.hyperspectral.extract_index` had been scaling the raw calculated array into a numpy uint8 array for plotting. Instead, after these updates the function will return the raw array that is calculated based on the index selected and instead there is a scaled image stored in the `pseudo_rgb` method of the `Spectral_data` object that is created. 
#203 

Stop scaling calculated indices

---

plantcv/plantcv/hyperspectral/__init__.py
plantcv/plantcv/hyperspectral/_avg_reflectance.py
plantcv/plantcv/hyperspectral/_inverse_covariance.py
tests/tests.py

Add helper functions that can allow users to use data read in with PlantCV and then go on to use GatorSense functions. Specifically, this PR includes the addition of two function. The `_inverse_covariance` will calculate an inverse covariance matrix given a hyperspectral data instance. The `_avg_reflectance` function finds the average masked reflectance given a hyperspectral data instance and a binary mask. 
Is this a:
* New feature 
* closes #494 
* closes #495 
* #203 
These functions are included in the `init` file and have testing coverage but I have not written any documentation since these functions are not expected to get used by the average PlantCV user.

Hyperspectral helpers

---

docs/transform_correct_color.md
plantcv/plantcv/transform/color_correction.py

In `plantcv.transform.create_color_card_mask()` the exclude input option required users to input excluded color chip IDs in descending numerical order. Based on #389 this pull request automatically sorts the user input chip IDs.
Is this a feature enhancement.
Closes #389
No changes to tests were needed. The docstring and documentation were updated to remove reference to the need to provide sorted inputs.

Sort excluded color chips

---

tests/tests.py

A change (possibly a new version of matplotlib) is causing two tests to fail when the a matplotlib plot is saved as JPG with the backend used in the testing environment. Simple solution is to output in a supported format (PNG).
Is this a:
* Bug fix

Output test images as PNG

---

plantcv/plantcv/hyperspectral/analyze_spectral.py

While running `pcv.print_results` after collecting data from the updated `pcv.hyperspectral.analyze_spectral` function (which was updated since v3.7 and now includes std) there was an error printing out data since json files cannot handle float32. 
Is this a:
* Bug fix

analyze_spectral bugfix w print_results

---

plantcv/plantcv/analyze_bound_horizontal.py
plantcv/plantcv/analyze_bound_vertical.py
plantcv/plantcv/analyze_nir_intensity.py
plantcv/plantcv/analyze_object.py
plantcv/plantcv/cluster_contour_splitimg.py
plantcv/plantcv/naive_bayes_classifier.py
plantcv/plantcv/opening.py
plantcv/plantcv/resize.py

Noticed that a handful of PlantCV functions would save out debugging images as JPEGs rather than PNGs, which is what the majority of images saved out will be. Updated functions so that they filetype is consistent.

Consistent debugging img filetype

---

docs/updating.md
docs/within_frame.md
environment.yml
plantcv/plantcv/within_frame.py
tests/tests.py

In working on a dataset with @phloz we found that even though plants were growing out of frame, `in_bounds` was always `True`. In the particular workflow the single border pixels around the image were clear of plant pixels (due to an erosion I think). This pull request adds a `border_width` parameter to `plantcv.within_frame` that allows the user to specify how many pixels from the image edge they want to consider for detecting out-of-frame objects. The default is 1 px, which maintains the previous default behavior.
Is this a:

Add border width to within_frame

---

docs/analyze_index.md
docs/updating.md
plantcv/plantcv/hyperspectral/analyze_index.py
plantcv/plantcv/hyperspectral/extract_index.py
tests/tests.py

Minimum and maximum bin parameters now control range of histogram values. There was a plotting mismatch between histogram plotting and calculation since the range for frequency values used to be independent of `min_bin` and `max_bin`. 
Is this a:
* Bug fix
* Feature enhancement
#203 
#526

Analyze index march2020 updates

---

plantcv/plantcv/hyperspectral/analyze_index.py

Auto version of min/max bins could cause internal `cv2.calcHist` function to fail because it doesn't like the datatype, but casting it to float resolves the problem. The user input min/max is not affected at all with this. 
* Bug fix
#203 
#535 

force min/max bin values to float datatype in analyze_index

---

plantcv/plantcv/hyperspectral/extract_index.py

Non-asci character was used and threw error:
SyntaxError: Non-ASCII character '\xe2' in file plantcv/plantcv/plantcv/hyperspectral/extract_index.py on line 85, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Replaced rogue character with ascii character

fixed symbol causing error

---

plantcv/plantcv/hyperspectral/extract_index.py

The `extract_index` function from the hyperspectral sub-package was copying the dictionary and array data before extract VIs but this is not necessary and will run up the memory needed for a hyperspectral session. 
Is this a:
#203 
Tested and significantly reduced the amount of memory used in an interactive session while carrying out the same workflow steps on the same image data.

stop copying the data, just reference it instead to save memory

---

docs/custom_range_threshold.md
docs/nir_tutorial.md
docs/updating.md
plantcv/plantcv/threshold/threshold_methods.py

The function `pcv.threshold.custom_range` had an input parameter named `rgb_img` which is inaccurate since the function also works on grayscale images. These updates correct the parameter name to the more general `img` in 
Is this a:
* Bug fix
* closes #546

update param name from rgb_img to img

---

plantcv/plantcv/rectangle_mask.py
plantcv/plantcv/threshold/threshold_methods.py

This one has been bugging me a while. when thresholding and making rectangle mask the debug images are displayed in the opposite order that they are output.  I can never remember the order and that should be an intuitive reminder.
Is this a:
* Bug fix
no issues
Does not break output, only the order that debug='plot' images are displayed.

changed order of debug images to match output

---

docs/analyze_NIR_intensity.md
plantcv/plantcv/analyze_nir_intensity.py

Add median, mean, and stdev to observations being collected into the Outputs class during the `pcv.analyze_nir` function. Tested to make sure the pixels are being masked properly (0 pixels won't skew summary stats, only data within masked region gets used) and updated docs. 
Is this a:

Add NIR summary stats 

---

Dockerfile

Attempting to run the PlantCV Docker image resulted in an error: `ImportError: libGL.so.1: cannot open shared object file: No such file or directory` as noted in #579. To fix this the apt package `libgl1-mesa-glx` package needs to be installed in the container. This pull request installs it and changes the name of the `opencv` conda package used to be consistent with the `bioconda` PlantCV package.
Closes issue #579 
Merging this PR with master will immediately trigger a new Docker build to fix the issue without a new official release.

Update Dockerfile recipe to fix missing libGL dependency

---

docs/transform_correct_color.md
docs/updating.md
plantcv/plantcv/transform/color_correction.py
tests/tests.py

Extend the `pcv.transform.find_color_card` function to optionally measure the average chip size and record it to the Outputs class as an observation. 
Users can avoid measuring the average chip size, and choose to use either mean or median as the measure. This capability could remove the need for size markers in images that already have color cards being used for preprocessing. 
[x] update docs
[x] add/update unit testing
[x] add observation to outputs

Add chip size to find color card

---

plantcv/plantcv/transform/color_correction.py

Differences in output from `cv2.minAreaRect` in OpenCV < 3.4.10 and 3.4.10 order width and height differently. We use the ratio of width / height to find contours that are square-ish in `pcv.transform.find_color_card`. To normalize the ratio, this pull request updates `find_color_card` to sort the width and height values and take the ratio of the longest / shortest. Since we do not use the orientation of the bounding rectangle in this function, this meets our purpose of determining which boxes are approximately square.
Is this a: Bug fix - it will allow us to pass tests with OpenCV >= 3.4, including 3.4.10.

Sort width and height to normalize ratio

---

.github/workflows/continuous-integration.yml
.github/workflows/publish-package.yml

This PR updates our continuous integration and delivery workflows in a few ways:
1. Updates GitHub Actions checkouts from their new default (main) branches.
2. Runs tests in the packaging workflow using `pytest` directly to bypass an issue on macOS and Windows.
3. Makes the `deploy` packaging Actions job dependent on the proceeding `build` job. I.e. we should only upload packages to PyPI if tests pass. 

Update CI/CD workflows

---

Dockerfile

The `Dockerfile` had hardcoded dependencies for PlantCV. When we change dependency versions or add/remove dependencies, we have to update `requirements.txt`, `environment.yml` (for user convenience), and `Dockerfile`. This pull request modifies the `Dockerfile` to install dependencies (other than OpenCV) from the `requirements.txt` file instead. The Docker container should now be built with the correct dependencies each time without manually updating the `Dockerfile`.
The Docker container has not been updating recently due to failed builds. In addition to the fix above, I enabled notifications from Docker Hub so we will be made aware of any container build failures.

Update Dockerfile to fix outdated dependencies

---

.github/workflows/publish-package.yml

Fixes the GitHub Actions release deployment workflow. We need to install PlantCV before running tests.

Fix PlantCV release deployment workflow

---

.github/workflows/publish-package.yml

By default, tags are not cloned by checkout. Versioneer needs tags to create a valid version tag. Without a valid version deployment to PyPI fails.

Update deployment workflow to checkout all commits and tags

---

plantcv/plantcv/__init__.py
plantcv/plantcv/plot_image.py
plantcv/plantcv/threshold/threshold_methods.py
plantcv/plantcv/visualize/pseudocolor.py

I removed the plotting in pseudocolor() when debug=None because it causes issues if the matplotlib backend is not set correctly.  I also removed setting the display in  `__init__.py` because I think matplotlib takes care of this appropriately.  I added a plt.close() for the current figure at the end of pseudocolor() if debug=None.  this prevents the duplicate colorbars when running pseudocolor() multiple times but does NOT prevent the return of the figure handle. see comments in #620 for example.
I tested is on Windows with an ipython terminal, a .py script run with ipython, and using the plantcv workflow method. I also tested with debug='plot' and debug='print' in an ipython terminal on Windows.  Also tested successfully with jupyter notebook  …

fix plotting bug when debug=None

---

environment.yml

prioritize conda-forge over defaults channel in dev environment  to match channel used for release dependencies

preference to conda-forge

---

.gitattributes

use .gitattributes to force unix line endings so windows git doesnt think there were a million changes
exclude windows specific files like .cmd and .bat
https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files
windows woes

force unix line endings except for any windows specific files

---

plantcv/plantcv/hyperspectral/analyze_index.py

Update the function `pcv.hyperspectral.analyze_index` to be more robust to NaN values and to also only consider finite values when calculating index statistics even when values range to positive or negative inifinity. 
Is this a:
- closes #632 

filter on finite, and calc stats ignoring nan

---

plantcv/parallel/job_builder.py

The workflow parallelization was duplicating the name of the image for the metadata "image". Removed the concatenation of the path (including name) and the name. 
Is this a bug fix

fix duplicate on workflow metadata image (path+name+name)

---

docs/hyperspectral_tutorial.md
docs/vis_nir_tutorial.md

Changed rgb_img to img inside of the pcv.apply_mask() parameters for the vis-nir and hyperspectral tutorials.
Is this a:
* Bug fix
#692

Pcv.apply mask rgb img to img

---

docs/fill_segments.md
plantcv/plantcv/morphology/fill_segments.py
tests/tests.py

We added the functionality to fill in and measure the entire stem as one entity, but didn't specifically record a separate observation while doing so. This update makes it so that you can record a general "segment_area" or get out info about "stem_area" and "leaf_area" separately while providing the stem objects to the function separately. 
Is this a:
* Bug fix

Update fill segments measurements

---

docs/CONTRIBUTING.md
plantcv/plantcv/_debug.py
plantcv/plantcv/analyze_color.py
plantcv/plantcv/analyze_object.py
plantcv/plantcv/readimage.py
tests/tests.py

Adds a private function `_debug` that handles the decision-making to save or display visuals for debugging steps. The if/elif blocks in each PlantCV function that determine whether to use `pcv.print_image` or `pcv.plot_image` can be removed and replaced with a call to `_debug`:
```python
from plantcv.plantcv import params
from plantcv.plantcv._debug import _debug
_debug(visual=img, filename=os.path.join(params.debug_outdir, str(params.device) + "_debug_img.png")
```
Tests for each PlantCV function will no longer need to run each function with debug = "print" or "plot" enabled.
#706, #713

Create debug module

---

docs/cluster_contours_splitimg.md
docs/multi-plant_tutorial.md
docs/updating.md
plantcv/plantcv/cluster_contour_splitimg.py
tests/tests.py

Previously the splitimg() function did not take in non RGB images, which was changed.
Is this a:
#700

Pcv.cluster contours splitimg accept non rgb images

---

docs/Spectral_data.md
docs/hyperspectral_tutorial.md
docs/jupyter.md
docs/morphology_tutorial.md
docs/nir_tutorial.md
docs/outputs.md
docs/params.md
docs/print_results.md
docs/psII_tutorial.md
docs/roi_multi.md
docs/thermal_tutorial.md
docs/updating.md
docs/vis_nir_tutorial.md
docs/vis_tutorial.md
docs/watershed.md
plantcv/plantcv/analyze_object.py
plantcv/plantcv/classes.py
plantcv/plantcv/print_results.py
tests/data/data_results.csv
tests/tests.py

As discussed in #689, this PR adds a new method (`save_results`) to the `Outputs` class. `Outputs.save_results` supports two output formats, JSON and CSV. The code from `plantcv.print_results` was moved to the `save_results` method and a deprecation warning is now printed via `print_results`. When run with `outformat = "json"`, `Outputs.save_results` has the same functionality as `plantcv.print_results`. When run with `outformat = "csv"`, a single CSV table in "long" format is produced that is compatible with use in R. CSV format is useful for a user who runs workflows only in Jupyter or wants to utilize data for testing from Jupyter. The output format JSON must be used for parallel workflows as before.
If we adopt this change, users will need to migrate …

Add method to Outputs class to save results in multiple formats

---

plantcv/utils/sample_images.py

The coverage report for the current version of `pcv.utils.sample_images` sometimes loses coverage on a line based on whether or not a random integer is chosen twice by chance. This PR updates the random sampling method to choose a range of random array indices using the `random.sample` approach to choose `num` random indices without replacement in one selection instead of in a loop. This should stabilize coverage.
Is this a:
* Feature enhancement

Update random sample method

---

plantcv/plantcv/analyze_bound_horizontal.py
plantcv/plantcv/analyze_bound_vertical.py
plantcv/plantcv/analyze_object.py

Somehow when using `OpenCV` version (3.4.14) several function would not perform as expected, because of the updated `OpenCV` function `pointPolygonTest`, these functions are: `analyze_bound_horizontal`, `analyze_bound_vertical`, `analyze_object`. This pull request deals with this issue and is expected to be merged so that new pull requests would be based on this one. 
Is this a:
* Bug fix

Updates for opencv updates

---

environment.yml
plantcv/plantcv/visualize/hyper_histogram.py
requirements.txt

@DannieSheng this PR is an updated version of the visualize_hyper_histogram branch that uses a different method for converting wavelengths to RGB color values. I'm a little concerned about using the code from http://www.noah.org/wiki/Wavelength_to_RGB_in_Python because the license is not clear.
As an alternative, I found the package `colour-science` (https://www.colour-science.org/) that has a lot of cool features and can convert wavelengths to other color models. The code here uses it instead for you to review. It can convert wavelengths between 390 and 830 nm. I'm not sure it's still working with the non-visible wavelengths like you had it before:

Use colour-science package for wavelength conversion

---

tests/tests.py

I realized the tests for `transform_warp` were not placed together with other `transform` functions, so I moved these tests.
Is this a:
* Bug fix
* Small changes in `tests.py`

relocate tests for `transform_warp`

---

plantcv/plantcv/hyperspectral/read_data.py

Fix header format issue to read wavelength values containing a space before a newline in the opening `{` bracket. Also I needed to lowercase `Wavelength` string. [Here](https://gist.github.com/typelogic/2fc0611e02e4a3af8ee3268d43b85275) is the spectral header file where it failed to parse. 
* Bug fix
I got this spectral datasets [here](https://sites.google.com/site/hyperspectralcolorimaging/dataset/fruits)

Fix format for my header

---

plantcv/plantcv/find_objects.py

Cast the contours output from cv2.findContours as a list (they now are given as a tuple) 
Is this a:
* Bug fix
Some morphology tests failed in the unrelated PR #829. 
The problem seems to be that in the version of OpenCV used by the tests in GitHub (3.4.16.57) the contours in findContours
are given as a tuple instead of as a list. Those tests pass locally using OpenCV 3.4.14.

cast contour tuple as a list in find_objects

---

plantcv/plantcv/transform/color_correction.py

Scale color correction matrices to 0-255 in quick_color_check. After the last update the values of the matrices are between 0-1 but 0-255 is better for visualization
Is this a:
* Bug fix
Complements PR #829 

scale color correction matrices to 0-255 in quick color check

---

.github/workflows/publish-package.yml

Updates the GitHub Actions workflow `publish-package.yml` to trigger when a release is published rather than when it is created. This will allow for draft releases.
Closes #809

Trigger GitHub Actions deployment workflow when a release is published

---

.github/workflows/continuous-integration.yml
.github/workflows/publish-package.yml
Dockerfile
environment.yml
plantcv/plantcv/roi/roi_methods.py
requirements.txt

OpenCV v3 builds in conda-forge no longer have newer versions of Python, which is starting to cause issues building the plantcv-feedstock. This PR releases v3 pins on OpenCV to allow for builds with OpenCV4. It also shifts CI tests from Python v3.6-3.8 to v3.7-3.9.
Is this a: Update to dependencies
Closes #667

Update dependency OpenCV to v4

---

plantcv/plantcv/cluster_contour_mask.py
plantcv/plantcv/hyperspectral/extract_wavelength.py
plantcv/plantcv/morphology/analyze_stem.py
plantcv/plantcv/morphology/check_cycles.py
plantcv/plantcv/morphology/find_branch_pts.py
plantcv/plantcv/morphology/find_tips.py
plantcv/plantcv/morphology/prune.py
plantcv/plantcv/morphology/segment_angle.py
plantcv/plantcv/morphology/segment_combine.py
plantcv/plantcv/morphology/segment_curvature.py
plantcv/plantcv/morphology/segment_euclidean_length.py
plantcv/plantcv/morphology/segment_id.py
plantcv/plantcv/morphology/segment_insertion_angle.py
plantcv/plantcv/morphology/segment_path_length.py
plantcv/plantcv/morphology/segment_skeleton.py
plantcv/plantcv/morphology/segment_sort.py
plantcv/plantcv/morphology/segment_tangent_angle.py
plantcv/plantcv/morphology/skeletonize.py
plantcv/plantcv/output_mask_ori_img.py
plantcv/plantcv/spectral_index/spectral_index.py
plantcv/plantcv/threshold/threshold_methods.py
plantcv/plantcv/transform/color_correction.py
plantcv/plantcv/transform/nonuniform_illumination.py
plantcv/plantcv/transform/rescale.py
plantcv/plantcv/transform/resize.py
plantcv/plantcv/transform/rotate.py
plantcv/plantcv/visualize/clustered_contours.py
plantcv/plantcv/visualize/colorspaces.py
tests/tests.py

Finish converting functions to using the `_debug` module.
Is this a: Feature enhancement
Closes #713

Finish refactor debugging

---

plantcv/utils/sample_images.py

add in a line return to the step where new snapshot info CSVs are getting printed out
Is this a:
* Bug fix
- closes #855 

add line return to Sample Images function

---

plantcv/utils/converters.py

When converting JSON file to csv, the multi-trait lines that do no have values (i.e. NA) are missing the 'sample' column/value (line 76) as compared to the normal case (line 73). 
`csv.write(",".join(map(str, meta_row + [var, "NA", "NA"])) + "\n")`
The 'sample' value was added to the list on line 73. 
`csv.write(",".join(map(str, meta_row + [sample, var, "NA", "NA"])) + "\n")`
Is this a:
* Bug fix
This change closes issue #881.
Before this modification the resulting csv file could result with some rows having one too few columns, resulting in errors during import (at least this was the case using fread of the data.table library from R). With this change everything appears normal.

added sample column to case without variables

---

plantcv/plantcv/transform/color_correction.py
tests/plantcv/transform/test_color_correction.py

Modify the color correction functions so they work with all unsigned integer and float  dtypes (assuming images are between 0-1 for floats).
The normalization to work with values between 0-1 is done depending on the dtype and the corrected image has the same dtype as the source image.
Is this a:
* Bug fix
#883 
Before this PR the source and target images were normalized by dividing by 255 which is only valid for uint8 dtype

support for other dtypes in color correction

---

plantcv/plantcv/hyperspectral/read_data.py

dtype_dict in read_data.py associated np.uint64 to both 14 and 15 ENVI header data type
Is this a:
* Bug fix

fix bug in dtype_dict in hyperspectral read_data

---

plantcv/plantcv/crop.py
plantcv/plantcv/hyperspectral/_avg_reflectance.py
plantcv/plantcv/hyperspectral/_inverse_covariance.py
plantcv/plantcv/hyperspectral/extract_wavelength.py
plantcv/plantcv/morphology/_iterative_prune.py
plantcv/plantcv/morphology/analyze_stem.py
plantcv/plantcv/morphology/check_cycles.py
plantcv/plantcv/morphology/find_branch_pts.py
plantcv/plantcv/morphology/find_tips.py
plantcv/plantcv/morphology/prune.py
plantcv/plantcv/morphology/segment_angle.py
plantcv/plantcv/morphology/segment_combine.py
plantcv/plantcv/morphology/segment_curvature.py
plantcv/plantcv/morphology/segment_euclidean_length.py
plantcv/plantcv/morphology/segment_id.py
plantcv/plantcv/morphology/segment_insertion_angle.py
plantcv/plantcv/morphology/segment_path_length.py
plantcv/plantcv/morphology/segment_skeleton.py
plantcv/plantcv/morphology/segment_sort.py
plantcv/plantcv/morphology/segment_tangent_angle.py
plantcv/plantcv/transform/nonuniform_illumination.py
plantcv/plantcv/transform/rescale.py
plantcv/plantcv/visualize/colorize_masks.py
plantcv/plantcv/visualize/colorspaces.py
plantcv/plantcv/visualize/histogram.py
plantcv/plantcv/visualize/overlay_two_imgs.py

deepsource.io identified several docstrings that were overindented.
Is this a: minor code quality improvement

Fix overindented docstrings

---

environment.yml
plantcv/plantcv/hyperspectral/read_data.py
requirements.txt
tests/plantcv/hyperspectral/conftest.py
tests/plantcv/hyperspectral/test_read_data.py

Updates the `pcv.hyperspectral.read_data.py` file to introduce a new method to handle pattern matching between data and header filenames. 
Is this a:
Issue #915

Hsi filename pattern matching

---

plantcv/utils/sample_images.py
tests/utils/conftest.py
tests/utils/test_sample_images.py

`plantcv.utils.sample_images` (used by `plantcv-utils.py sample_images`) was not updated to handle `phenodata` datasets (see #923). This PR refactors `sample_images` to modularize the code and adds a sampling method for `phenodata` datasets.
Closes #923 

Update sample_images to handle phenodata datasets

---

plantcv/plantcv/segment_image_series.py

segment_image_series called numpy.save in a for loop within an expression that creates an unassigned list. 
Deepsource recommends not to do that. I replaced the expression with an explicit for loop. 
Is this a:
* Deepsource fix 

replace list expression with explicit for loop in segment_image_series

---

.gitattributes

To avoid conversion of line endings between Windows, macOS, and Linux systems when cloning the git repository, we specify in `.gitattributes` that some file types should be treated as binary and remain unmodified. This PR adds .gif file types to that list.

Add gif to gitattributes to treat as binary

---

.github/workflows/continuous-integration.yml

Updates the GitHub Actions workflow to run CI workflow on the `release-4.0` branch. Branch settings were also updated to protect the branch and require PRs to update and reviews before merging.
Is this a: Update
The branch `release-4.0` will be used to collect the remaining breaking changes mapped out for the v4.0 release.

Enable actions release4

---

plantcv/plantcv/_helpers.py
plantcv/plantcv/analyze_bound_horizontal.py
plantcv/plantcv/analyze_bound_vertical.py
plantcv/plantcv/analyze_object.py
plantcv/plantcv/crop_position_mask.py
plantcv/plantcv/find_objects.py
plantcv/plantcv/morphology/_iterative_prune.py
plantcv/plantcv/morphology/check_cycles.py
plantcv/plantcv/morphology/find_branch_pts.py
plantcv/plantcv/morphology/find_tips.py
plantcv/plantcv/morphology/prune.py
plantcv/plantcv/morphology/segment_curvature.py
plantcv/plantcv/morphology/segment_euclidean_length.py
plantcv/plantcv/morphology/segment_insertion_angle.py
plantcv/plantcv/morphology/segment_skeleton.py
plantcv/plantcv/morphology/segment_tangent_angle.py
plantcv/plantcv/rectangle_mask.py
plantcv/plantcv/report_size_marker_area.py
plantcv/plantcv/roi/roi_methods.py
plantcv/plantcv/roi_objects.py
plantcv/plantcv/visualize/obj_size_ecdf.py

We utilize `cv2.findContours` throughout PlantCV and use a mixture of directly using the OpenCV function or use the PlantCV wrapper `find_objects`. In most cases it's simpler to use the OpenCV function rather than using the PlantCV wrapper within the code. Additionally, if OpenCV ever changes the function signature then PlantCV has to be changed in many places. This PR adds a helper function that calls `cv2.findContours` and replaces direct usage throughout PlantCV to use the helper function. 
Is this a: Code refactoring

Add helper function to centralize usage of OpenCV findContours

---

docs/roi_rectangle.md
docs/updating.md
plantcv/plantcv/roi/roi_methods.py
tests/plantcv/roi/test_roi.py

Update `pcv.roi.rectangle` to utilize the `Objects` class. 
Is this a:
- Related to #945 

Update roi rectangle objects class

---

docs/std_color_matrix.md
docs/updating.md
mkdocs.yml
plantcv/plantcv/transform/__init__.py
plantcv/plantcv/transform/color_correction.py
tests/plantcv/transform/test_color_correction.py

Add a function that helps us access the standard rgb values (hard coded) for the chips in the color cards.
This allow us to correct images with respect to the std values. 
Source: https://en.wikipedia.org/wiki/ColorChecker
Is this a:

standard color correction matrix function

---

environment.yml
requirements.txt

Temporarily pin matplotlib to < v3.6 due to issues with plotnine. After merging, sync changes with the 4.x and release-4.0 branches.

Pin matplotlib to < 3.6

---

environment.yml
requirements.txt
tests/plantcv/test_segment_image_series.py

This PR sets the `pcv.params.debug_outdir` to the test cache tmp directory for the test `test_segment_image_series` to prevent test files from being saved to the source directory. Minor code format changes are also included

Fix test cache dir

---

plantcv/parallel/multiprocess.py
tests/parallel/test_multiprocess.py

This PR simplifies the `pcv.parallel.multiprocess` function to use the Dask client map function to submit jobs to the cluster. Map creates a futures object that can then be monitored with `progress`. The aim here is to properly populate the client cluster and shut it down upon completion to eliminate client errors that have been oberved.
#922

Reconfigure dask futures and client management

---

docs/analyze_spectral.md
plantcv/plantcv/hyperspectral/analyze_spectral.py
tests/plantcv/hyperspectral/test_analyze_spectral.py

There was duplicate observations of global standard deviation within the `pcv.hyperspectral.analyze_spectral` function when we probably intended to include the wavelength averages calculated earlier in the function and then plotted out. This PR resolves these bugs and renamed the variable to be more accurate throughout the function. 
Is this a:
* Bug fix
- Closes #962 

Add wavelength means Observation to analyze_spectral function

---

.github/workflows/continuous-integration.yml
.github/workflows/publish-package.yml
environment.yml
plantcv/plantcv/closing.py
plantcv/plantcv/threshold/threshold_methods.py
plantcv/plantcv/watershed.py
requirements.txt

Currently, when installing plantcv, the following error is raised: `ImportError: cannot import name 'greycomatrix' from 'skimage.feature'`
This is because skimage.feature changed their function name from greycomatrix to graycomatrix (see https://stackoverflow.com/questions/67537650/cannot-import-name-graycomatrix-from-skimage-feature ) from version 0.19. This commit changes the requirements.txt file and the function name.

Fix ImportError in plantcv caused by change in skimage.feature function name

---

plantcv/plantcv/fill.py

The check threw an error when the image was just black (only zeros) which broke workflows with images where no plant was visible.
The check now raises an error if the number of unique values in the array is larger than 2. Before, it was checking if the number was NOT exactly two. An image with just zeros and ones can still be processed. 
Is this a:
* Bug fix
None
None

Fixed check for binary image

---

docs/analyze_thermal_values.md

Typo fix to mask in thermal_hist.
Is this a:
Issue #999 
None

Typo fix to mask in thermal_hist

---

docs/visualize_colorspace.md

Changed "plantcv.visualize.colorspaces(rgb_img, **originial**_img=True)" to plantcv.visualize.colorspaces(rgb_img, **original**_img=True)."
Update to documentation
Issue #999 
N/A

Fixed typo in visualize_colorspace.md

---

.github/PULL_REQUEST_TEMPLATE.md

PR template link was based on `stable` doc URL. Changed PR template link to `latest` branch.
Updated PR template link so doc URL is based off `latest` branch.
Is this a:
* Bug fix
Issue #918 

Update PULL_REQUEST_TEMPLATE.md changed PR template link from stable branch to latest branch.

---

docs/pr_review_process.md

Added pytest-cov install instructions for pr_review instructions
Is this a:
update to documentation

1018 add install pytest cov to contribution guide

---

plantcv/plantcv/fill_holes.py
plantcv/plantcv/median_blur.py

Changed the namespace for two functions being imported ( `scipy.ndimage.morphology` ->  `scipy.ndimage` , and `scipy.ndimage.filters` -> `scipy.ndimage`) in `fill_holes.py` and `median_blur.py`.
Is this a:
* Bug fix (fixing a deprecation warning)
See comments in #999
None

Scipy ndimage namespace fix 

---

plantcv/plantcv/analyze_object.py

Removed an `else: pass` section after an `if area:` which was suspected to be a problem line for code coverage checks.
Is this a:
* housekeeping
See #999 
None

removed an 'else: pass' from analyze_object

---

plantcv/plantcv/classes.py
plantcv/plantcv/roi/roi2mask.py
tests/plantcv/test_Objects.py

these changes.
Is this a:
* Bug fix

make Objects class return Objects instance while iterating

---

docs/scharr_filter.md

Changed print to plot in scharr_filter.md

---

docs/roi_objects.md

Issue #999 
Missed this one when I changed the first print.

Changed second print to plot in roi_objects.md

---

plantcv/plantcv/analyze_nir_intensity.py
plantcv/plantcv/visualize/histogram.py

The helper function `_hist_gray` ignores the `lower_bound` input when calculating the minimum image value. It uses a hard-coded value of 5000 the set masked values to a negative number, but for some images the minimum observed value is > 5000, causing a false peak in the grayscale histogram. This PR reduces the complexity of the function and fixes the bug.

Simplify histogram code and fix bug in minimum value calculation

---

plantcv/plantcv/threshold/threshold_methods.py

function `threshold.dual_channels` was returning a binary image of `dtype` depending on the type of `max_value`. By default and most of the time it returned a 64 bits image which is incompatible with the rest of PlantCV functions.  
Is this a:
* Bug fix

Fix threshold dual channels returning bad dtype

---

plantcv/plantcv/threshold/threshold_methods.py

dual threshold bugfix propogated down
Is this a:
* Bug fix

Release 4.0 bugfix

---

plantcv/plantcv/morphology/fill_segments.py
plantcv/plantcv/segment_image_series.py

Scikit-image stopped converting the input markers to watershed to int32 by default and we do not explicitly define the data type of markers in `pcv.segment_image_series` or `pcv.morphology.fill_segments`. Tests started failing with scikit-image v0.21.

Define type for markers in watershed

---

docs/analyze_grayscale.md
docs/updating.md
mkdocs.yml
plantcv/plantcv/analyze/__init__.py
plantcv/plantcv/analyze/grayscale.py
tests/plantcv/analyze/test_grayscale.py

Create a new function to analyze grayscale pixel values, `pcv.analyze.grayscale`, that utilizes labeled masks. Ultimately replaces `pcv.analyze_nir_intensity`.

Iterate analyze grayscale

---

plantcv/plantcv/morphology/fill_segments.py

Fixes an issue where newer versions of scikit-image do not coerce markers in watershed to int32

Add type to markers

---

plantcv/utils/converters.py

`json2csv` checks for `list` and `tuple` data types and unpacks them into a long-format CSV output file. But when the value is a list of tuples, for storing coordinates, it was outputting the comma-delimited coordinates into the CSV output, which caused the table to be parsed with an uneven number of columns.
This PR checks the type of the data contained in the enclosing list or tuple and skips it if it is also a list or tuple.
#1191

Skip CSV output for x-y points

---

docs/find_color_card.md

Update doc page so that the `label` parameter is included while calling `find_color_card` rather than `create_color_card_mask`. 
Is this a:
* typo fix

find_color_card typo fix, move "label" param into correct function

---

plantcv/plantcv/threshold/threshold_methods.py

This PR Builds on: 
* #1218 
* #1219 
* Removes max_val param from the threshold._call_threshold internal method
feature enhancement
completes one task from this ticket: https://github.com/danforthcenter/plantcv/issues/1194

remove max_val param from threshold._call_threshold()

---

plantcv/plantcv/threshold/threshold_methods.py

This PR Builds on: 
* #1219 
* #1220 
* Removes max_val param from the threshold._call_adaptive_threshold internal method
feature enhancement
completes one task from this ticket: https://github.com/danforthcenter/plantcv/issues/1194

remove max_val param from threshold._call_adaptive_threshold()

---

docs/threshold_dual_channels.md
docs/updating.md
plantcv/plantcv/threshold/threshold_methods.py
tests/plantcv/threshold/test_threshold_methods.py

* Removes max_val param from the threshold.dual_channels method
* updates function documentation
* updates updating.md
* fixes tests broken by change
feature enhancement
completes one task from this ticket: https://github.com/danforthcenter/plantcv/issues/1194

remove max_val param from threshold.dual_channels()

---

README.md

Adds a template to `README.md` for a contributors table, populated by a bot action: https://allcontributors.org/docs/en/bot/usage. The purpose is to broaden recognition of both code and non-code contributors.

Add all-contributors table and badge

---

.readthedocs.yaml

Read the Docs announced they are deprecating builds for repositories that are missing the `.readthedocs.yaml` configuration file: https://blog.readthedocs.com/migrate-configuration-v2/.
This PR adds the configuration file. Our build is pretty basic so the default minimal configuration is added.

Add config file for Read the Docs

---

docs/analyze_npq.md
docs/analyze_yii.md
docs/photosynthesis_read_cropreporter.md
docs/photosynthesis_reassign_frame_labels.md
docs/tutorials/psII_tutorial.md
docs/visualize_chlorophyll_fluorescence.md
environment.yml
plantcv/plantcv/analyze/npq.py
plantcv/plantcv/analyze/yii.py
plantcv/plantcv/classes.py
plantcv/plantcv/photosynthesis/read_cropreporter.py
plantcv/plantcv/photosynthesis/reassign_frame_labels.py
plantcv/plantcv/visualize/chlorophyll_fluorescence.py
requirements.txt
tests/conftest.py
tests/plantcv/analyze/test_npq.py
tests/plantcv/analyze/test_yii.py
tests/plantcv/photosynthesis/conftest.py
tests/plantcv/photosynthesis/test_psii_data.py
tests/plantcv/photosynthesis/test_read_cropreporter.py
tests/plantcv/photosynthesis/test_reassign_frame_labels.py
tests/plantcv/test_plot_image.py
tests/plantcv/test_print_image.py
tests/plantcv/test_show_dataarray.py
tests/plantcv/visualize/test_chlorophyll_fluorescence.py

Renames `PSII_data` dataset attributes from `darkadapted` and `lightadapted` to `ojip_dark` and `ojip_light`, based on the name of the method, OJIP. This will allow future addition of PAM measurements.

Update PSII dataset names

---

docs/gaussian_threshold.md
docs/mean_threshold.md
docs/updating.md
plantcv/plantcv/threshold/threshold_methods.py
tests/plantcv/threshold/test_threshold_methods.py

For consistency, call the parameter `ksize` instead of `block_size` since we use `ksize` for kernel size elsewhere. 
Is this a:
* Update
#1304 

Rename to ksize in adaptive thresholding methods 

---

mkdocs.yml

Functions are organized by common purpose or data type. For example, all analysis functions are organized in `plantcv.analyze`. The documentation TOC follows this logic, but in some cases it is useful to also link to a function based on a shared set of functionality, such as all functions related to Hyperspectral image analysis.
This PR adds duplicate links to the TOC of the documents so that functions can be found both in their actual submodule but also in relevant groupings based on function. In particular, duplicate links are added to the `hyperspectral` and `photosynthesis` sections, and a new `Inputs and Outputs` section is added at the top to make the basic data handling functions easier to find.
**For …

Add extra table of contents links

---

docs/parallel_config.md
docs/pipeline_parallel.md
plantcv/parallel/__init__.py
tests/testdata/workflowconfig_template.json

Fixes warning from Dask Jobqueue:
>FutureWarning: job_extra has been renamed to job_extra_directives. You are still using it (even if only set to []; please also check config files). If you did not set job_extra_directives yet, job_extra will be respected for now, but it will be removed in a future release. If you already set job_extra_directives, job_extra is ignored and you can remove it.

Rename job_extra to job_extra_directives

---

plantcv/plantcv/create_labels.py

`pcv.create_labels` was incorrectly setting the number of labels to the number of unique labels in the labeled mask. When plants are missing and ROIs are supplied, this can under count the number of labels. Instead we changed the number of labels to the number of input ROIs, when relevant.

Set num_labels to num ROIs

---

plantcv/utils/converters.py

The `json2csv` function uses Pandas `pivot_table` to make a wide format CSV file for singe-value traits. Because we pivot on the `trait` and `label` columns, this creates a hierarchical header. In implementing this change for 4.0 we left off the code to collapse the headers into a single set of column names.

Collapse hierarchical headers for CSV files

---

environment.yml
plantcv/plantcv/classes.py
requirements.txt

Removes upper limit on matplotlib versions and fixes one issue in `Points` related to changes to the `matplotlib` API. The change is backwards compatible with older versions of matplotlib.

Update matplotlib supported versions

---

docs/analyze_bound_horizontal2.md
docs/analyze_bound_vertical2.md
docs/analyze_color2.md
docs/analyze_grayscale.md
docs/analyze_npq.md
docs/analyze_size.md
docs/analyze_spectral_index.md
docs/analyze_spectral_reflectance.md
docs/analyze_thermal.md
docs/analyze_yii.md
docs/outputs.md
plantcv/plantcv/_helpers.py
plantcv/plantcv/analyze/npq.py
plantcv/plantcv/analyze/yii.py
tests/plantcv/analyze/test_bound_horizontal.py
tests/plantcv/analyze/test_bound_vertical.py
tests/plantcv/analyze/test_color.py
tests/plantcv/analyze/test_grayscale.py
tests/plantcv/analyze/test_npq.py
tests/plantcv/analyze/test_size.py
tests/plantcv/analyze/test_spectral_index.py
tests/plantcv/analyze/test_spectral_reflectance.py
tests/plantcv/analyze/test_thermal.py
tests/plantcv/analyze/test_yii.py
tests/plantcv/test_helper_iterate_analysis.py

Modifies the helper function `_iterate_analysis` to accept either a string label or a list of labels equal to the length of `n_labels`. If a string is input, a list of length `n_labels` is made by repeating the input string. The iterator uses the list of labels to label each object label. If the length of labels is not equal to `n_labels` a fatal error is triggered.
We might need to update all analysis doc pages to indicate that a list of labels can be input.
Is this a:
#1360 

Enable multi label input

---

docs/read_image.md
docs/roi2mask.md
docs/updating.md
plantcv/plantcv/floodfill.py

Two doc bug fixes. Typo in `pcv.roi2mask` doc page and fix the parameter name in `updating.md` for `pcv.flood_fill` which has the plural `points` parameter now. 
Is this a:
* Bug fix
- closes #1371  
- 

Documentation minor bug fixes

---

docs/photosynthesis_read_cropreporter.md
plantcv/plantcv/photosynthesis/read_cropreporter.py

Updates the wavelengths assigned to spectral frames in CropReporter datasets to:
* 640, 550, 475nm are Red, Green, Blue
* 540, 710, 770nm are Anthocyanin, red-Edge, NIR
The existing wavelengths could cause some spectral indices to be computed with the incorrect frame: see #1373.
Closes #1373

Update spectral wavelengths for CropReporter datasets

---

plantcv/plantcv/annotate/points.py

Changed the block comments from double hash symbols (##) to single hash symbols (#) for consistency with standard Python commenting practices.
these changes.
Is this a:
* Bug fix

too many leading '#' for block comment

---

plantcv/plantcv/hyperspectral/write_data.py
plantcv/plantcv/visualize/pixel_scatter_vis.py

Changed two places where one blank line was between classes and functions per deepsource recommendation
Is this a deepsource fix.

changes for deepsource expecting 2 blank lines

---

plantcv/plantcv/classes.py

Removed a redundant specification about the Points class taking an object per deepsource recommendation.
Is this a deepsource fix.

removing redundant object specification

---

plantcv/plantcv/watershed.py

Changed default params.color_sequence behavior for watershed. Color_sequence default is now random and restored alongside params.debug.
#1428
Unsure if further implementation required.

Randomize color order default for pcv.watershed()

---

docs/transform_detect_color_card.md
plantcv/plantcv/transform/detect_color_card.py

Add min_size to `detect_color_card` kwargs
Is this a:
*  feature enhancement
Low resolution images plus small color card varieties can make color cards too small for detection at the default 1000 pixel filtering size. Enable users to lower this if it helps in their dataset. 

Add min_size to `detect_color_card` kwargs

---

.deepsource.toml
.github/workflows/continuous-integration.yml
README.md
tests/plantcv/test_plot_image.py

Updates the codecov GitHub Action to v4.1.0 and adds a test to cover a missing line in `plot_image` for `altair` charts.

Update codecov action

---

docs/roi_quick_filter.md
docs/updating.md
mkdocs.yml
plantcv/plantcv/roi/__init__.py
plantcv/plantcv/roi/quick_filter.py
tests/plantcv/roi/test_quick_filter.py

Adds a new function `plantcv.roi.quick_filter` that is a companion to `plantcv.roi.filter`. The new function is significantly faster than `filter` but only supports the ROI partial overlap method (`roi_type="partial"` in `filter`).

Add method to quickly filter binary images

---

plantcv/learn/__init__.py

We recently added a new feature that cross imported from the `learn` submodule, which contains code that checks the environment and sets `matplotlib` to a non-plotting backend if needed. But this caused PlantCV imports to switch `matplotlib` to the `agg` backend unintentionally, which breaks the plotting debug mode. This PR removes the unneeded `matplotlib` backend code from the `learn` submodule.

Fix bug in plotting debug mode

---

docs/transform_calibrate_camera.md
docs/transform_checkerboard_calibration.md

Changed listed input parameters and code block from "mtx" and "dist" to "mtx_filename" and "dist_filename."
Is this a:
#1504 

Fixed error in documentation for camera calibration

---

docs/parallel_config.md
docs/roi_auto_grid.md

Change during v4 allows for simpler syntax for Windows users, now command is the same? 
Is this a:
* Bug fix
- closes #1514 
- 

parallel docs for windows Update

---

docs/io_open_url.md
docs/updating.md
mkdocs.yml
plantcv/plantcv/io/__init__.py
plantcv/plantcv/io/open_url.py
tests/plantcv/io/test_open_url.py

Adds the function `plantcv.io.open_url` to read grayscale or RGB image data from a URL (HTTP/HTTPS). 
Closes #1367
One use of this function is for tutorials, particularly in Colab where only the tutorial notebooks are opened and data from the corresponding repository is not cloned automatically.

Read images over HTTP

---

MANIFEST.in

Prunes the tests, docs, and vice folders from the PyPI source distribution package (sdist) to decrease the size of the source package to below the 100MB limit on PyPI.

Prune test and doc files from sdist

---

pyproject.toml

Limits maximum NumPy version to exclude v2 for now to avoid breaking changes.

Pin NumPy to v1.x

---

plantcv/plantcv/spectral_index/spectral_index.py

When calculating vegetative indices it is common to have zero value and NaN value pixels that trigger divide by zero and divide by invalid number warnings. This PR temporarily suppresses these NumPy warnings in the `spectral_index` functions.
#1566

Suppress divide by zero and invalid number warnings

---

tests/plantcv/filters/test_filter_objs.py
tests/plantcv/homology/test_acute.py
tests/plantcv/test_debug.py

During tests, many warnings are due to matplotlib being unable to open a display. To reduce the number of warnings, only tests that need to test plotting should have the plot debug mode turned on. Because it is a global parameter, turning it on leaves it on for other tests. This PR turns it off after plot is turned on for specific tests.
Is this a: cleanup
#1566

Turn plotting off after use in tests to avoid warnings

---

plantcv/plantcv/homology/constella.py
plantcv/plantcv/homology/space.py
plantcv/plantcv/morphology/analyze_stem.py
plantcv/plantcv/morphology/segment_angle.py
plantcv/plantcv/morphology/segment_insertion_angle.py
plantcv/plantcv/morphology/segment_tangent_angle.py

In NumPy 1.25, casting single value arrays to Python data types is deprecated. In general this PR extracts the single value before casting to fix the issue (or avoids casting when unnecessary).
Is this a: cleanup
#1566

Fix casting issues that trigger NumPy deprecation warnings

---

docs/Spectral_data.md
environment.yml
plantcv/plantcv/classes.py

Some functions in the add-on packaged plantcv-geospatial benefit from having additional metadata stored as attributes of spectral_data objects. This PR adds geo_transform and geo_crs, the affine transformation matrix to convert from geo referenced coordinates to raster coordinates and the coordinate system respectively. Because they are both added with appropriate defaults (the identity matrix and "None"), this change should not affect any core plantcv functions. 
* New feature or feature enhancement (kind of)

Add geospatial attributes to spectral_data class

---

docs/Spectral_data.md
plantcv/plantcv/classes.py

Previously, we had added some additional attributes to the `spectral_data` class to accommodate some of the metadata associated with geospatial data. This PR now replaces those individual metadata terms with an attribute called "metadata". The default is an empty dictionary, but it can be populated with any number of keys specific to various data types, like hyperspectral and geospatial.    
Is this a:

Add metadata attribute to spectral_data class

---

plantcv/plantcv/warn.py
tests/plantcv/test_warn.py

The existing `warn` function prints a warning message to STDERR. This PR updates the function to print when `pcv.params.verbose` is `True` but not `False`. This allows the user to suppress warning messages when needed. Also adds an explicit test for the `warn` function.

Update warn to utilize the verbose global parameter

---

plantcv/plantcv/roi/roi_methods.py

Creating multiple ROIs in the context of 10s of ROIs has not been an issue, but creating 100s of ROIs is slow. This PR aims to make adjustments to ROI functions to improve performance.

Speed improvements for creating multiple ROIs

---

docs/updating.md
docs/visualize_obj_size_ecdf.md

Update docs to reflect the latest syntax of `pcv.visualize.obj_size_ecdf` 
Is this a:
- closes #1620 
- thank you to @hkmanching for bringing this issue to our attention 

Obj size ecdf docs bugfix

---

plantcv/plantcv/fill_holes.py

Changing data type check for catching grayscale and rgb while still allowing a pure black/white mask
these changes.
Bug fix
#1635 
N/A

Update d type in fill_holes.py check 

---

plantcv/plantcv/visualize/colorize_masks.py

A couple of the named colors available in `visualize.colorize_masks` had color values that differed from what was listed on the linked web page. This PR fixes those values.
Is this a:
* Bug fix
Closes #1701 

Fix colors in `visualize.colorize_masks`

---

plantcv/plantcv/transform/color_correction.py

This PR modernizes NumPy array stacking in the color chip data preparation pipeline by replacing deprecated aliases.
It solves the following warnings which you can find in the [CI logs](https://github.com/danforthcenter/plantcv/actions/runs/14978034653/job/42075204720#step:6:471): 
```python
DeprecationWarning: row_stack alias is deprecated. Use np.vstack directly.
```
It also fixes a few typos along the way.
Is this a:
* Bug fix

Update array stacking for color standard processing

---

plantcv/plantcv/_helpers.py
plantcv/plantcv/report_size_marker_area.py
plantcv/plantcv/rgb2gray.py
plantcv/plantcv/rgb2gray_cmyk.py
plantcv/plantcv/rgb2gray_hsv.py
plantcv/plantcv/rgb2gray_lab.py
plantcv/plantcv/segment_image_series.py
plantcv/plantcv/threshold/threshold_methods.py
plantcv/plantcv/transform/checkerboard_calib.py
plantcv/plantcv/transform/detect_color_card.py
plantcv/plantcv/transform/nonuniform_illumination.py
plantcv/plantcv/visualize/colorspaces.py
plantcv/plantcv/visualize/pixel_scatter_vis.py

The `rgb2gray` color conversion functions are reused throughout PlantCV, which may cause circular import issues. This PR creates new helper functions for each type of color conversion, refactors the user-facing functions as wrappers for the helpers, and refactors other functions that use color conversion to use the helper functions instead to avoid import conflicts.
Is this a: code cleanup
#1704

Create helpers for color conversion

---

environment.yml
pyproject.toml

`statsmodel` is not currently compatible with `scipy` 1.16: https://github.com/statsmodels/statsmodels/issues/9542
Is this a: dependency fix

Pin scipy to <1.16

---

plantcv/plantcv/morphology/segment_skeleton.py

The `segment_objects` returned by `pcv.morphology.segment_skeleton` is supposed to be a list of OpenCV contours. This change casts the tuple type list of objects into a proper `list` type object.
Is this a:
* Bug fix
- closes #1719 
It appears that something upstream changed within `cv2.findContours` which formats the contours inside a tuple. This causes an error downstream within the `pcv.morphology.fill_segments` analysis function, since `tuple` type objects are not supported with the operation `.copy()` which the function does to preserve the input list of objects/contours.
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to …

`morphology.segment_skeleton` returned segment_objects to list

---

plantcv/plantcv/readbayer.py
tests/plantcv/test_readbayer.py

Restructures the `pcv.readbayer` function to reduce cyclomatic complexity.
Is this a: code cleanup

Reduce cyclomatic complexity readbayer

---

plantcv/plantcv/kmeans_classifier.py
tests/plantcv/test_kmeans_classifier.py

Updates `predict_kmeans` to input a ndarray directly instead of reading from a file. Removes a circular import.
Is this a: minor update

Update kmeans inputs

---

docs/roi_auto_wells.md
docs/updating.md
plantcv/plantcv/roi/roi_methods.py
tests/plantcv/roi/test_roi.py

Added regional filtering to `pcv.roi.auto_wells` per [1753](https://github.com/danforthcenter/plantcv/issues/1753).
Minimal example syntax:
```
import cv2
import numpy as np
from plantcv import plantcv as pcv 
%matplotlib widget
pcv.params.debug = "plot"
img = cv2.imread("/home/josh/plantcv/tests/testdata/circle-wells.png", -1)
rois = pcv.roi.auto_wells(img, 20, 50, 30, 40, 50, 4, 6, -10)
rect = pcv.roi.rectangle(img, x=50, y =50, h=450,  w=350)
print(rect.contours)
rois2 = pcv.roi.auto_wells(img, 20, 50, 30, 40, 50, 4, 6, -10, roi=rect)
```
This is a new feature or feature enhancement and should close [1753](https://github.com/danforthcenter/plantcv/issues/1753)
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to …

Hough circle regional filter

---

docs/analysis_approach.md
docs/faq.md
docs/transform_detect_color_card.md

Add some context to documentation page `transform_detect_color_card.md` and add mention of color standardization to the `faq.md`. Added size standardization mention to `analysis_approach.md`. 
- Update to documentation
- Closes #1675
- Color cards are the way that we recommend to do size and color standardization of images within a dataset. We've added recent functionality to help with quality control for inaccurate detection. Detection of color cards is sensitive to other objects in the image such (e.g. calculator buttons and tape grids and additional color cards). Understanding how the detection algorithm works will hopefully prevent some known issues from being introduced during image capture protocol. Best practice is to …

update FAQ to mention color standardization

---

tests/plantcv/io/test_open_url.py

One of the tests for `open_url` uses a GIF hosted at Wikipedia and the test now fails. I suspect we were accessing the image programmatically enough that we were blocked. This PR changes to a self-hosted synthetic GIF image.

Use a self-hosted image for testing
