danforthcenter/plantcv

- .gitignore
Merge updates gitignore to ignore mkdocs _build directories
> Updating gitignore to ignore _build/*

- plantcv/cluster_contours.py
updated cluster contours function so it does not use numpy digitize
> Cluster contour

- docs/installation.md
Added Cloud9 IDE install information to Installation.md file for web browser code development within Chromebooks or similar thin clients.
> Add Cloud9 IDE install information

- plantcv/analyze_color.py
Debug images were not printing if output images were disabled.
> Debug conditional relied on the filename conditional

- .travis.yml
Switched from compiling OpenCV (slow) to installing via conda
> Use conda to install OpenCV

- plantcv/analyze_color.py
Removed a check for filename that was preventing debug from working
when no output image files were requested. Should allow images to be
plotted in Jupyter again.
> Removed unused logical check

- .travis.yml
- setup.py
Expanded installation requirements to 'cv2', 'matplotlib', 'numpy', 'pandas', 'python-dateutil', 'pytest', 'scipy', 'scikit-image'
> Added all installation requirements

- docs/installation.md
- plantcv-pipeline.py
- plantcv/get_nir.py
This pull request fixes a few issues on Windows platforms.
1. `plantcv-pipeline.py` was making temp directories with ":" in the name, which Windows does not allow. Changed to "-" instead.
2. `plantcv-pipeline.py` was importing `.tab` files into the SQLite database with a shell command that used single-quotes around the import statement. Windows did not like this, so the commands were updated to use double-quotes.
3. Windows installation instructions were updated to install requirements using Anaconda.
4. The function `get_nir()` had hard-coded "/" path joins, which do not work on Windows. The function was updated to use `os.path.join` instead for cross-platform compatibility.
> Fix Windows issues

- plantcv/analyze_NIR_intensity.py
[ ] Relevant tests (and test data) have been added or updated and passed.
[ ] The documentation was added or updated.
[ ] Relevant issues were updated or added.
> fixed histogram, and disentangled debug and output statements.

- docs/machine_learning_tutorial.md
- docs/naive_bayes.md
- mkdocs.yml
- plantcv-train.py
- plantcv/learn/__init__.py
- plantcv/learn/naive_bayes.py
- setup.py
- tests/tests.py
This pull request creates a new subpackage (`plantcv.learn`) and moves several functions (mainly naive_bayes) from `plantcv-train.py` to the subpackage. Documentation and unit tests were added for the naive_bayes training module.
> Update naive bayes feature

- .travis.yml
Travis-CI is phasing out the Ubuntu 12.04 VM-based build environments
(sudo: required). We should no longer need sudo, so this pull request tests
the container-based (sudo: false) build environment.
For more information, see: https://blog.travis-ci.com/2017-04-17-precise-EOL
> Change to sudo-less builds

- tests/tests.py
This pull request addresses issue #161 where tests failed on Windows because of a file name conflict in the tests cache directory. Two features were added to fix the issue. First, a setup and teardown method were added to create and delete the cache directory. Second, within the cache directory, a test-specific directory is made to avoid collisions between tests.
Bug fix
> Bug fix 161

- plantcv/learn/naive_bayes.py
Updating graph output formats to SVG (vector drawing) for easy incorporation into figures for publication. This pull request will also be updated to try to add log-likelihood graphs for the classifier.
This is an enhancement to existing functionality
> Updating/adding plots to the naive Bayes training and classifier methods

- plantcv-pipeline.py
- utils/db-exporter-pcv2.py
- utils/db-get_raw_images_and_masks_semirandom.py
- utils/db-get_raw_images_flex.py
- utils/db-get_raw_images_random.py
- utils/util-append-file-image-name.py
- utils/util-avg_background_img.py
- utils/util-downsize-images.py
Mostly minor code formatting fixes for PEP8 compliance. Some utility scripts were updated to match the newer database structure.
Minor updates
> Update util scripts

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Fixed a link in ReadMe
- Added a note on a potential source of PR/Issue template confusion
- One other cosmetic change
No changes to code.
See also http://github.com/danforthcenter/plantcv-web/pull/2
I also have some FAQ updates that I will try to push soon.
- [NA] Relevant tests (and test data) have been added or updated and passed.
- [y] The documentation was added or updated.
- [NA] Relevant issues were updated or added.
> Minor documentation improvements

- docs/machine_learning_tutorial.md
- docs/pipeline_parallel.md
- plantcv-pipeline.py
`plantcv-pipeline.py` was updated to use the `subprocess.call` method without a shell (either `call([...], shell=True)` or `os.system(...)`). This should improve cross-platform compatibility and is intended to fix potential issues arising from running pipelines on files with spaces and other escapable characters.
Bug fix
> Fix potential issues analyzing image files with spaces or escapable characters

- docs/analysis_approach.md
- mkdocs.yml
> added image analysis approaches doc

- docs/CONTRIBUTING.md
- docs/analysis_approach.md
- docs/faq.md
Minor updates to Analysis Approaches, FAQ, and Contribution Guide sections.
Minor formatting, grammar, etc. updates.
> Some general editing of the documentation

- docs/index.md
- mkdocs.yml
This PR adds links to all the main documentation pages to the documentation overview page (index.md). It tries to briefly describe the context of the pages so that people know where to look for information. It also reorganizes the table of contents somewhat. In particular, the three sections related to contributing are now grouped in a subsection.
Minor documentation improvement.
> Update main docs page

- docs/db-exporter.md
- docs/index.md
- mkdocs.yml
Some minor tweaks to the documentation
> A few more doc edits

- plantcv/__init__.py
This is a small update that adds a class called Params to PlantCV. Params is initialized with default values in the namespace `plantcv.params`. Right now params holds two values, `plantcv.params.device` and `plantcv.params.debug` (default values 0 and None, respectively). This class will be used to simplify our API per discussion in issue #202. Right now there should be no real effect on functionality.
New feature
> New feature add init class

- docs/white_balance.md
changed errors
removed 'A gray scale' as this is incorrect
added 'mode=' for consistency
added 'roi=' as an error occurs without it ' SyntaxError: positional argument follows keyword argument'
Fixed errors in the documentation
-  The documentation was added or updated.
> update to white_balance.md

- docs/adaptive_threshold.md
Updated namespace for adaptive_threshold function. 
Documentation
> Updated namespace for adaptive_threshold function.

- .travis.yml
- plantcv/plantcv/analyze_NIR_intensity.py
- plantcv/plantcv/triangle_auto_threshold.py
- tests/tests.py
Pull request #244 failed because of a build issue with Travis CI and Python3. I think the issue might be that we install OpenCV with Anaconda but install all the other Python dependencies with pip, creating some version mismatch. Since we routinely install everything with Anaconda I updated Travis CI to do the same.
Buggix
> Update Travis-CI to install dependencies with conda instead of pip

- plantcv-pipeline.py
Restructure parallelization using a simplified job stack and map. See issue #247
* The `job_builder` function builds a list of jobs instead of a list of list of jobs. This allows map to iterate over all jobs and replace finished jobs in the process queue immediately rather than splitting up jobs and having each CPU handle batch chunks.
* The `exe_multiproc` function now uses `multiprocessing.map` instead of `multiprocessing.map_async`. Map uses blocking, which is useful in this use case.
* The `process_images_multiproc` now just runs subprocess.call directly instead of iterating over a job list first.
Bug fix
> Process in parallel with map

- mkdocs.yml
- plantcv/plantcv/fill.py
- tests/tests.py
Updated fill function. Replaced internal code with a skimage function called remove_small_objects. Should increase speed of the function. Also updated test for the function to be more specific to the function. Closes issue #260
> Fill function update

- docs/median_blur.md
- plantcv/plantcv/median_blur.py
- tests/tests.py
Function uses spicy.ndimage.filters.median_filter. This allows more flexibility, (ksize X ksize) square kernel or (n,m) box kernel if user speficies a tuple. Added ksize input check to the function. Added test for additional if statement in the function that checks ksize type. median_filter function allows even kernel sizes. Updated documentation. Closes issue #259
> update median_blur function

- mkdocs.yml
The new documentation builds seem to use the mkdocs theme instead of the readthedocs theme. Added configuration to explicitly use readthedocs instead.
Bug fix
> Explicitly define readthedocs theme

- docs/installation.md
opencv needs to be installed before you can install plantcv
> updated installation order in Installation.md

- .travis.yml
In the existing Travis CI configuration we only triggered builds on the master branch (and pull requests). We added a feature to deploy on tagged commits but because we only do builds on master it ignored the tagged version and did not deploy. To fix this this pull request adds a regular expression to the branch build settings to look for tags also.
Bug fix
> add git tag regex to build rules

- MANIFEST.in
- setup.py
Updates the `setup.py` file to tell PyPI to render the `README.md` file as markdown.
Bug fix
> Render from markdown in PyPI

- docs/HistEqualization.md
- docs/analyze_color.md
- docs/median_blur.md
- docs/resize.md
- docs/rgb2gray.md
- docs/rgb2hsv.md
- docs/rgb2lab.md
- docs/transform_color_correction_tutorial.md
- docs/vis_nir_tutorial.md
- docs/vis_tutorial.md
Went through latest version of docs and found any broken links or other corrections.
> doc corrections

- .travis.yml
- README.md
- docs/installation.md
- environments/environment27.yml
Adds PyPI and Anaconda Cloud badges to the README and updates the installation instructions to add PyPI (pip) and conda install methods.
Documents new functionality
> Add pypi and conda install instructions

- mkdocs.yml
Adds a link in the table of contents to the PlantCV Hyperspectral subproject documentation.
Minor modification to the documentation to link to the hyperspectral subproject.
> Add link to hyperspectral docs

- plantcv/plantcv/dilate.py
- plantcv/plantcv/erode.py
- plantcv/plantcv/plot_hist.py
- tests/tests.py
Finally figured out why I wasn't seeing my dilate debug images. the print statement was using params.debug instead of params.debug_outdir.
Fixed.
> Bug! should be params.debug_outdir to print

- docs/analyze_color.md
- docs/output_measurements.md
- docs/updating.md
- docs/vis_nir_tutorial.md
- docs/vis_tutorial.md
- environment.yml
- plantcv-pipeline.py
- plantcv/plantcv/analyze_color.py
- plantcv/plantcv/analyze_nir_intensity.py
- plantcv/plantcv/print_results.py
- plantcv/plantcv/transform/color_correction.py
- requirements.txt
- tests/tests.py
- Added calculations for basic statistics for hue values of an image. It still needs some work to alighn with pcv standards.  I have opened this pull request as @HaleySchuhl reccomended this approach for collaboration.
- Closes #314 
Adds additional functionality to analyze color function
> Adding basic statistics to analyze color function

- docs/morphology_tutorial.md
- docs/report_size_marker.md
- requirements.txt
- A space in one of the python blocks was causing a bad artifact in the read the docs page
- Test to see if scipy and plotnine are getting along now
> Morphology Tutorial Correction 

- docs/morphology_tutorial.md
I merged the previous pull request too soon, there was one more space that needed to be removed in the docs.
> Remove space before code block

- README.md
Use a Bioconda badge in the README instead of the more generic Anaconda Cloud badge to display the current package version number.
Updates the README with a new badge.
> Use Bioconda badge

- plantcv/plantcv/x_axis_pseudolandmarks.py
- plantcv/plantcv/y_axis_pseudolandmarks.py
- plantcv/utils/converters.py
> Bug fix list observations

- Dockerfile
- docs/installation.md
Updating the Docker build recipe to use a Jupyter-based container with Python 3. Addresses issues #255 and #273
Updates the `Dockerfile` recipe and documentation.
> Update docker image

- mkdocs.yml
add thermal tutorial to table of contents
> add thermal tutorial to table of contents

- environment.yml
conda complains if pip is not included prior to using it
> include pip in environment.yml

- plantcv/plantcv/visualize/pseudocolor.py
fixed some formatting issues in docstring. added defaults for arguments
> updated docs in pseudocolor

- plantcv/plantcv/hyperspectral/analyze_spectral.py
Fix the bug with writing out temp files with data by changing data type.
> Hyperspectral group dev

- docs/updating.md
Added info about upgrading plantcv. 
Might need more info for PyPI - I've never used that. Also for containers and Cloud9 install.
> add info about upgrading plantcv

- plantcv/plantcv/roi/roi_methods.py
- tests/tests.py
Print warning if user defined ROI's in multi.roi overlap at all
closes #481
> print warning if user defined ROI's overlap at all

- plantcv/plantcv/hyperspectral/analyze_spectral.py
Collect data about pixelwise standard deviation. 
Is this a:
#203
> add std to analyze_spectral function

- docs/CONTRIBUTING.md
Minor syntax fix in CONTRIBUTING.md (missing "return")
Is this a:
> Syntax fix in CONTRIBUTING.md

- docs/analyze_spectral.md
- plantcv/plantcv/hyperspectral/analyze_index.py
- plantcv/plantcv/hyperspectral/analyze_spectral.py
- plantcv/plantcv/hyperspectral/read_data.py
- plantcv/plantcv/morphology/segment_insertion_angle.py
- tests/tests.py
The `pcv.hyperspectral.analyze_spectral` function was storing out information, mainly about the global statistics like the maximum reflectance value for the entire datacube. Average reflectance per band was the only per-band measurement that we had been doing but really most of the stats could be per-band rather than global. 
Also, need to cast datatype of measurements getting stored out during the `analyze_index` function. 
Make sure docs reflect updates 
#203
> Update analyze_spectral measurements

- .gitignore
- docs/gaussian_blur.md
- docs/pipeline_parallel.md
Made some updates to the documentation based on this week's usage on Windows.
Is this a:
> Doc updates

- docs/hyperspectral_tutorial.md
- docs/visualize_clustered_contours.md
- mkdocs.yml
This pull request fixes a few missing pages and broken links within the documentation.
Is this a:
> Fix missing docs pages

- docs/stdev_filter.md
fix links to screen shots in stdev_filter doc page 
Is this a:
* Bug fix
> fix links to screen shots in doc page

- plantcv/plantcv/analyze_color.py
hue_median was getting saved as hue_median and hue_circular_std. fixed so hue_circular_std is used for hue_circular_std
Is this a:
* Bug fix
> fix copy paste error

- plantcv/plantcv/hyperspectral/read_data.py
- tests/hyperspectral_data/darkReference_darkReference.hdr
* closes #565 
Is this a:
* Bug fix
*  feature enhancement
> Update read envi

- README.md
- docs/calibrate.md
- docs/index.md
- docs/roi_ellipse.md
- docs/vis_tutorial.md
- plantcv/plantcv/roi/roi_methods.py
Updates the documentation and README file to fix a few typos/formatting issues and update some content for relevance to the current version of PlantCV.
* Updates the VIS tutorial to fix issues found in #585 
* Updates the `plantcv.roi.ellipse` documentation/docstring to switch the axis order as discovered in #589
* Updates the README and docs homepage per #507
> Update documentation and README

- Dockerfile
- docs/parallel_config.md
- docs/parallel_multiprocess.md
- docs/pipeline_parallel.md
- environment.yml
- plantcv-workflow.py
- plantcv/parallel/__init__.py
- plantcv/parallel/multiprocess.py
- requirements.txt
- tests/parallel_data/workflow_config_template.json
- tests/tests.py
This pull request builds on #607 and should not be merged until after it is merged. Here, we remove the older Python multiprocessing parallelization feature and replace it with a configurable [Dask](https://dask.org/) cluster. Python multiprocessing was local parallelization (i.e. computing took place where the program `plantcv-workflow.py` was run). This functionality is maintained by using the `dask.distributed` `LocalCluster` option. However, using `dask-jobqueue`, we now support remote, distributed computing using cluster options available through [dask-jobqueue](https://jobqueue.dask.org/en/latest/), currently: HTCondorCluster, LSFCluster, MoabCluster, OARCluster, PBSCluster, SGECluster, and SLURMCluster.
To configure the parallel computing environment, you …
> Add distributed computing feature

- plantcv/plantcv/analyze_color.py
- plantcv/plantcv/analyze_nir_intensity.py
- plantcv/plantcv/analyze_thermal_values.py
- plantcv/plantcv/hyperspectral/analyze_index.py
- plantcv/plantcv/hyperspectral/analyze_spectral.py
- plantcv/plantcv/photosynthesis/analyze_fvfm.py
- plantcv/plantcv/print_image.py
- plantcv/plantcv/threshold/threshold_methods.py
- plantcv/plantcv/transform/color_correction.py
- plantcv/plantcv/visualize/histogram.py
- tests/tests.py
This pull request aims to create/update tests to cover the final 6 lines of code not reached by current tests.
* 2 lines were not reached due to typos in their test functions
* 2 tests were added to test the handling of plotnine plots with the print and plot functions
* 2 lines were removed because they can likely never be reached
Additionally, now when saving plotnine figures `verbose=False` was added to the `save` commands to suppress the warnings.
Is this a: feature enhancement
> 100% testing coverage

- README.md
This pull request replaces the conda badge with a conda-forge badge. It also updates some Markdown syntax for better compatibility between Markdown interpreters.
> Update readme to replace conda badge

- docs/vis_tutorial.md
Updated the vis-tutorial and deleted "rgb_" from the "img".
Is this a:
* Bug fix
#692
> Fix syntax error in apply_mask

- docs/multi-plant_tutorial.md
- docs/psII_tutorial.md
- docs/rotate2.md
- docs/updating.md
- plantcv/plantcv/rotate.py
- plantcv/plantcv/transform/__init__.py
- plantcv/plantcv/transform/rotate.py
- tests/tests.py
Moved the rotate function to the transform sub-package
Created a pcv.rotate placeholder so the rotate function is backwards compatible
Is this a:
#657
> Relocate rotate

- docs/outputs.md
- plantcv/plantcv/__init__.py
- plantcv/plantcv/classes.py
- tests/tests.py
Check datatype for added observation in function add_observation of plantcv Output class.
Is this a:
Addressed the issue discussed in #701
> Add json datatype check in add observation

- docs/multi-plant_tutorial.md
- docs/updating.md
- docs/visualize_clustered_contours.md
- plantcv/plantcv/visualize/clustered_contours.py
- tests/tests.py
bounding parameter added to clustered_contours() function so circles can be turned on or off (defaulted as on)
Is this a:
#718
> Pcv.visualize.clustered contours optional bounding circles

- plantcv/plantcv/cluster_contour_splitimg.py
- tests/tests.py
Adding the _debug update to cluster_contours_splitimg() and tests.py for the splitimg function.
Is this a:
#713
> Cluster contours splitimg debug update

- plantcv/utils/sample_images.py
img_element_array now stores the relative path of the images (root+file). That is all that is needed for the part that copies the images.
Is this a:
* Bug fix
The function was not working properly if the image database contained sub-folders
> Bug sample images subfolders

- plantcv/plantcv/cluster_contours.py
- plantcv/plantcv/visualize/pseudocolor.py
converted these to base python classes `int` and `bool`
> numpy is deprecating `np.int` and `np.bool`

- plantcv/plantcv/fill.py
- tests/tests.py
Updated the debug module on the fill function
Is this a:
#713
> Update debug module fill

- plantcv/utils/sample_images.py
Get 4.x up to date with the main branch to get the bug fix for the sample images function
Is this a:
#855 
> Update with master

- .deepsource.toml
Adds deepsource.io configuration file to the repository to enable automated code review.
> Add deepsource.io config file to repository

- .coveragerc
Fixes coverage by omitting the whole `_version.py` file from `versioneer`
> Omit coverage for the file _version.py

- docs/updating.md
- docs/visualize_colorspace.md
added original_img optional parameter to documentation in visualize_colorspace.md and updating.md
Is this a:
closes #893 
> update documentation for visualize_colorspace

- .github/PULL_REQUEST_TEMPLATE.md
- docs/pr_review_process.md
- mkdocs.yml
Created a new documentation page for reviewing pull requests, based on [this](https://docs.google.com/document/d/1NbCROJ7gJeZQI2264UiPYxkSwPDe4isxxh2rrKrwjR4/edit) google doc
> New docs page for pr review process

- docs/params.md
Updating params class to have default values
#898
> add default values

- .gitattributes
Apply updates to v3 to the v4 branch
> Apply bugfix to v4

- README.md
- docs/CODE_OF_CONDUCT.md
Replaces our custom code of conduct with the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org) (version 2.1). Adds a badge to link to the code of conduct in the README.
Is this a: Update
Closes #588
Merge after PR #940 
> Update code conduct

- docs/roi_ellipse.md
- docs/updating.md
- plantcv/plantcv/roi/roi_methods.py
- tests/plantcv/roi/test_roi.py
Update `pcv.roi.ellipse` function and related files to implement the use of Objects class. 
Is this a:
* Enhancement
- #945 
> Update roi.ellipse to use objects class

- docs/find_objects.md
- docs/updating.md
- plantcv/plantcv/find_objects.py
- tests/plantcv/test_find_objects.py
Implement the `Objects` class into the `pcv.find_objects` functionality and reflect those changes in testing and documentation. 
Is this a:
*  feature enhancement
#946 
> Update find objects objects class

- environment.yml
- requirements.txt
Syncs changes in the main branch with the 4.x branch
> Pin matplotlib version

- docs/roi2mask.md
- docs/updating.md
- plantcv/plantcv/roi/roi2mask.py
- tests/plantcv/roi/test_roi2mask.py
these changes.
Is this a:
* Bug fix
> use objects class in roi2mask

- docs/analyze_spectral.md
- plantcv/plantcv/hyperspectral/analyze_spectral.py
- tests/plantcv/hyperspectral/test_analyze_spectral.py
> Update release 4.0

- docs/analyze_shape.md
changed "print" to "plot" as a debug
Is this a:
Issue #999
> Changed print to plot in analyze_shape.md

- docs/analyze_color.md
Changed print to plot in analyze_color 
Is this a:
#999
> Change print to plot in analyze color

- docs/save_matrix.md
Removed quotations from filename.
Previous markdown had quotations surrounding `filename`. Quotations were removed.
'filename' -> filename
Is this a:
Issue #999
None
> Update save_matrix.md to remove quotations surrounding filename

- docs/installation.md
Changed `installation.md` file to say it tests python 3.8, 3.9, and 3.10
- Update to docs
#999 
No additional context
> test PR, changed python versions listed for testing

- docs/analyze_spectral.md
Changed pcv.params.debug = "**print**" to pcv.params.debug = "**plot**"
Issue #999 
N/A
> Changed print to plot in analyze_spectral.md

- docs/analyze_stem.md
> Changed print to plot in analyze_stem.md

- docs/watershed.md
> Changed print to plot in watershed.md

- docs/white_balance.md
Changed print to plot in white balance
Is this a:
#999
> changed white balance print to plot

- docs/flip.md
update print to plot in gaussuan_threshold.md
Is this a:
#999
> Update_print to plot_gaussian_threshold.md

- docs/erode.md
> Changed print to plot in erode.md

- docs/image_add.md
Changed print to plot in image_add
Is this a:
#999
> Update_image_add_print to plot

- docs/triangle_threshold.md
updated print to plot in triangle threshold
Is this a:
#999
> update print to plot in triangle_threshold

- docs/check_cycles.md
changed print to plot in check_cycles
Is this a:
#999 
> changed print to plot in check_cycles

- docs/transform_rescale.md
updated print to plot in the transform rescale
Is this a:
#999
> change print to plot transform rescale

- docs/fill_segments.md
> Changed print to plot in fill_segments.md

- docs/find_objects.md
changed print to plot in find_objects
Is this a:
#999
> Updated print to plot in find_objects

- docs/get_nir.md
changed print to plot in get_nir
Is this a:
#999
> updated print to plot in get_nir

- docs/fill_holes.md
> Changed print to plot in fill_holes.md

- docs/closing.md
> Changed print to plot in closing.md

- docs/invert.md
changed print to plot in invert
Is this a:
#999
> update print to plot in invert

- docs/cluster_contours_splitimg.md
> Changed print to plot in cluster_contours_splitimg

- docs/stdev_filter.md
Change print to plot in stdev_filter.md
Is this a:
issue #999 
none
> change print to plot stdev_filter.md

- docs/logical_or.md
Change print to plot in logical_or
Is this a:
#999
> Update_logical_or_print to plot

- docs/crop_position_mask.md
> Changed print to plot in crop_position_mask.md

- docs/roi_multi.md
changed print to plot in roi_multi
Is this a:
#999 
> changed print to plot in roi_multi

- docs/roi_from_binary_image.md
changed print to plot in roi_from_binary_image
Is this a:
#999 
> changed print to plot in roi_from_binary_image

- docs/spectral_index.md
updated print to plot in spectral_index
Is this a:
#999
> changed print to plot in spectral_index

- docs/roi_circle.md
changed print to plot in roi_circle
Is this a:
#999 
> change print to plot in roi_circle

- docs/custom_range_threshold.md
> Changed print to plot in custom_range_threshold.md

- docs/distance_transform.md
> Change print to plot in distance_transform.md

- docs/sobel_filter.md
change print to plot to sobel_filter.md
Is this a:
Issue #999 
None
> Change print to plot to sobel_filter

- docs/extract_wavelength.md
> Changed print to plot in extract_wavelength.md

- docs/gaussian_threshold.md
> Changed print to plot in gaussian_threshold.md

- docs/logical_xor.md
> Changed print to plot in logical_xor.md

- docs/nonuniform_illumination.md
> Changed print to plot in nonuniform_illumination.md

- docs/object_composition.md
> Changed print to plot in object_composition.md

- docs/otsu_threshold.md
> Changed print to plot in otsu_thresholds.md

- docs/output_mask.md
*Update to documentation
Issue #999 
N/A
> Changed print to plot in output_mask.md

- docs/photosynthesis_analyze_fvfm.md
> Changed print to plot in photosynthesis_analyze_fvfm.md

- environment.yml
- requirements.txt
Install pandas less than version 2.0
Bypass current build issues with Python 3.8
> Limit upper pandas version

- docs/rgb2lab.md
> Changed print to plot in rgb2lab.md

- docs/rgb2hsv.md
> Changed print to plot in rgb2hsv.md

- docs/rgb2gray.md
> Changed print to plot in rgb2gray.md

- docs/rgb2cmyk.md
> Changed print to plot in rgb2cmyk.md

- docs/report_size_marker.md
> Changed print to plot in report_size_marker.md

- docs/photosynthesis_read_cropreporter.md
> Changed print to plot in photosynthesis_read_cropreporter.md

- docs/read_bayer.md
> Changed print to plot in read_bayer.md

- docs/roi_objects.md
> Changed print to plot in roi_objects.md

- docs/scale_features.md
> Changed print to plot in scale_features.md

- docs/saturation_threshold.md
> Changed print to plot in saturation_threshold.md

- docs/rotate2.md
> Changed both prints to plot in rotate2.md

- docs/roi2mask.md
> Changed print to plot in roi2mask.md

- docs/roi_rectangle.md
> Changed print to plot in roi_rectangle.md

- docs/segment_angle.md
> Changed print to plot in segment_angle.md

- docs/segment_curvature.md
> Changed print to plot in segment_curvature.md

- docs/segment_euclidean_length.md
> Changed print to plot in segment_euclidean_length.md

- docs/segment_id.md
> Changed print to plot in segment_id.md

- docs/opening.md
> Changed both prints to plot in opening.md

- docs/segment_insertion_angle.md
> Changed print to plot in segment_insertion_angle.md

- docs/segment_pathlength.md
> Changed print to plot in segment_pathlength.md

- docs/segment_skeleton.md
> Changed print to plot in segment_skeleton.md

- docs/segment_sort.md
> Changed print to plot in segment_sort.md

- docs/segment_tangent_angle.md
Changed pcv.params.debug = **print** to pcv.params.debug = **plot**
Issue #999 
N/A
> Changed print to plot in segment_tangent_angle.md

- docs/shift.md
Changed pcv.params.debug = **print** to pcv.params.debug = **plot**
Issue #999 
N/A
> Changed print to plot in shift.md

- docs/opening.md
- docs/photosynthesis_read_cropreporter.md
- docs/read_bayer.md
- docs/read_image.md
- docs/rectangle_mask.md
- docs/report_size_marker.md
- docs/rgb2cmyk.md
- docs/rgb2gray.md
- docs/rgb2hsv.md
- docs/rgb2lab.md
- docs/roi2mask.md
- docs/roi_objects.md
- docs/roi_rectangle.md
- docs/rotate2.md
- docs/saturation_threshold.md
- docs/scale_features.md
- docs/scharr_filter.md
- docs/segment_angle.md
- docs/segment_curvature.md
- docs/segment_euclidean_length.md
- docs/segment_id.md
- docs/segment_insertion_angle.md
- docs/segment_pathlength.md
- docs/segment_skeleton.md
- docs/segment_sort.md
- docs/segment_tangent_angle.md
- docs/shift.md
Syncs changes from main to 4.x
> Update 4x with updates in main

- plantcv/plantcv/background_subtraction.py
Added warn functions, replacing print statements.
Is this a:
> Added-warn-function-replace-print

- plantcv/plantcv/cluster_contour_splitimg.py
Added warn function, replacing print statements.
Is this a:
> Add warn cluster contour splitimg

- plantcv/plantcv/object_composition.py
Add warn statement, replace print statement.
Is this a:
> Add-warn-replace-print-obj-comp

- plantcv/plantcv/roi_objects.py
Add warn statement, replace print statement.
Is this a:
> add-warn-replace-print-roi_objects

- plantcv/plantcv/hyperspectral/analyze_index.py
- tests/plantcv/hyperspectral/test_analyze_index.py
Added warn function, replacing the print statement.
Is this a:
> add-warn-replace-print-analyze_index

- plantcv/plantcv/roi/roi_methods.py
- tests/plantcv/roi/test_roi.py
Added warn function, replacing the print statement.
Is this a:
> add-warn-replace-print-roi_methods

- plantcv/plantcv/threshold/threshold_methods.py
Added warn function, replacing the print statement.
Is this a:
> add-warn-replace-print-threshold_methods

- plantcv/plantcv/_helpers.py
Added warn function, replacing the print statement.
Is this a:
> add-warn-replace-print-helpers

- docs/output_measurements.md
- mkdocs.yml
Removes deprecated functions from the TOC and reorganizes the `output_measurements.md` page to make it easier to update.
> Minor docs fixes

- docs/triangle_threshold.md
- docs/updating.md
- plantcv/plantcv/threshold/threshold_methods.py
- plantcv/plantcv/visualize/auto_threshold_methods.py
- tests/plantcv/threshold/test_threshold_methods.py
* Removes max_val param from the threshold.triangle method
* updates function documentation
* updates updating.md
* fixes tests broken by change
feature enhancement
completes one task from this ticket: https://github.com/danforthcenter/plantcv/issues/1194
> remove max_val param from threshold.triangle()

- .readthedocs.yaml
- README.md
- docs/find_color_card.md
- plantcv/plantcv/morphology/segment_sort.py
Syncs changes in main to the release-4.0 branch
> Update release-4.0 from main

- docs/tutorials.md
- docs/tutorials/watershed_segmentation_tutorial.md
updating watershed tutorials in gallery
these changes.
Is this a:
* Bug fix
> Update Watershed tutorial

- environment.yml
these changes.
Is this a:
* Bug fix
[skip ci]
> Limit jupyterlab [skip ci]

- docs/tutorials.md
- docs/tutorials/vis_nir_tutorial.md
Updates to plantcv docs pages that point to the updated tutorial for a dual VIS/NIR workflow. 
Is this a:
* Collaboration with @leowlima who did all the leg work of building a new GitHub repo and updating the actual tutorial to v4 syntax. Thanks!!!
#1293 
> Tutorial update vis nir

- docs/analyze_thermal.md
- docs/tutorials.md
- docs/tutorials/thermal_tutorial.md
Describe your changes
Updates to plantcv docs pages that point to the updated tutorial for a thermal workflow.
Type of update
Is this a:
Collaboration with @lacostag  who did all the leg work of building a new GitHub repo and updating the actual tutorial to v4 syntax. Thanks!!!
Update to documentation
Associated issues
https://github.com/danforthcenter/plantcv/issues/1293
> Tutorial Update thermal

- docs/tutorials.md
- docs/tutorials/vis_tutorial.md
I scrolled through @kmurphy61 's updates and made a branch which updates the links on the PlantCV tutorial page to point to this new VIS side view workflow. 
Is this a:
#1293 
> Update vis tutorial

- docs/tutorials.md
- docs/tutorials/machine_learning_tutorial.md
Update the links in docs to the new naive bayes/ML tutorial
Is this a:
https://github.com/danforthcenter/plantcv/issues/1293
https://github.com/danforthcenter/plantcv/issues/1293
https://github.com/danforthcenter/plantcv/issues/1304
> Update ml / Naive Bayes tutorial

- docs/tutorials.md
- docs/tutorials/input_output_tutorial.md
Collaboration with @joshqsumner who did all the leg work of building a new GitHub repo and updating the actual tutorial to v4 syntax. Thanks!!!
Is this a:
#1293 
> Update tutorial input output

- docs/updating.md
> Revise updating.md

- docs/installation.md
Simplify guide to core use cases
#1304
> Update installation guide

- docs/tutorials.md
- docs/tutorials/arabidopsis_multi_plant_tutorial.md
> Tutorial arabidopsis multi plant

- README.md
add deepsource badge
these changes.
Is this a:
- closes #1385 
- 
> Update README.md with Deepsource badge 

- plantcv/plantcv/visualize/pixel_scatter_vis.py
Made whitespace after "," and before new var
these changes.
Is this a:
* Bug fix
>  Whitespace after ","

- plantcv/plantcv/image_fusion.py
- plantcv/plantcv/photosynthesis/read_cropreporter.py
Placed quotations around dict()
Is this a:
PTC-W0019
> PTC-W0019 - Consider using literal syntax

- plantcv/plantcv/classes.py
- plantcv/plantcv/hyperspectral/write_data.py
- plantcv/plantcv/roi/roi_methods.py
- plantcv/plantcv/segment_image_series.py
- plantcv/plantcv/threshold/threshold_methods.py
Changed doc string conventions to align with best practices based on deepsource
Is this an update to documentation
> changing doc string conventions for deepsource best practices

- plantcv/plantcv/classes.py
Grouped imports for `classes.py` so that plantCV modules are loaded one after the other.
Is this a deepsource rcommendation
> grouping imports per deepsource

- plantcv/plantcv/morphology/__init__.py
Added a new line where code was longer than 127 characters per deepsource recommendation.
Is this a deepsource fix
> changing max linewidth in file

- plantcv/plantcv/threshold/threshold_methods.py
Removed variable that references itself
Is this a:
> Deleted variable mask=mask

- plantcv/plantcv/homology/acute.py
Changed comparison order in an if statement to align with deepsource's best practices.
Is this a stylistic edit via deepsource.
> changed comparison order per deepsource standards

- plantcv/plantcv/classes.py
added a line after docstring
Is this a:
Reference associated issue numbers. Does this pull request close any issues? FLK-D204
> added line after docstring

- plantcv/plantcv/visualize/colorspaces.py
bug fix to add padding when image widths unequal
these changes.
Is this a:
* Bug fix
> visualize.colorspaces.py bugfix

- plantcv/plantcv/visualize/__init__.py
remove extra line return
deepsource FLK-W391
> Deepsource fix remove extra line return in init file

- .github/workflows/continuous-integration.yml
Analyze coverage on project directory so Deepsource test-coverage works properly.
> Run pytest on the whole project directory

- .deepsource.toml
- .github/workflows/continuous-integration.yml
Exclude configs from coverage analysis
> Exclude configs from coverage analysis

- .deepsource.toml
Exclude more files from coverage analysis
> Exclude more files from coverage analysis

- plantcv/plantcv/image_fusion.py
- plantcv/plantcv/morphology/segment_combine.py
- plantcv/plantcv/shift_img.py
- plantcv/plantcv/white_balance.py
Fixed deepsource unused variable issues. Changed 6 instances of unused variable name assignments to "_" across 4 files.
Deepsource issue fix
> fix-PYL-W0612

- .coveragerc
Omit temp files created during opencv install in coverage analysis during pytest run.
Is this a: cleanup
> Clean up pytest errors

- docs/tutorials/vis_tutorial.md
> add buttons to vis tutorial

- plantcv/plantcv/analyze/bound_horizontal.py
- plantcv/plantcv/analyze/bound_vertical.py
- plantcv/plantcv/analyze/size.py
- plantcv/plantcv/visualize/hyper_histogram.py
Related to deepsource PYL-R1728
> Using generators instead of list comprehension

- plantcv/learn/cli.py
- plantcv/plantcv/classes.py
- plantcv/plantcv/create_labels.py
- plantcv/plantcv/roi/roi_methods.py
- plantcv/plantcv/threshold/threshold_methods.py
- plantcv/plantcv/white_balance.py
- plantcv/utils/cli.py
- plantcv/utils/converters.py
- plantcv/utils/sample_images.py
- tests/plantcv/test_output_mask.py
Related to deepsource PY-D0003
> Adding missing docstrings

- plantcv/parallel/parsers.py
Deepsource issue PYL-C0209 f string fix in parsers.py
> Deepsource f string fix

- docs/filters_obj_props.md
Commit 3c945a1204004f6613d5ff40398261aadb480882 renamed the filters obj props source code file. This PR adjusts sources to changes,
Is this a:
> Update obj props source code

- docs/updating.md
The example code for updating to version 4 appears to have a small bug. The variable `bin_img` is not defined before it is used, and the variable `bin_mask` is unused after defining. Moreover, making the change allows the sample code to run completely.
Is this a sample code bug fix.
None
None
> Minor example code fix

- plantcv/plantcv/closing.py
Fixing a typo
Is this a typo fix in a debug image label
> fixing typo

- tests/plantcv/test_output_mask.py
Addressing deepsource warning about potential unbalanced tuple unpacking.
This is a deepsource edit.
None
> manually unpacking tuple

- plantcv/plantcv/morphology/analyze_stem.py
- plantcv/plantcv/morphology/segment_angle.py
- plantcv/plantcv/morphology/segment_insertion_angle.py
- plantcv/plantcv/morphology/segment_tangent_angle.py
Trying to reduce cyclomatic complexity in `morphology.segment_insertion_angle` 
This is a deepsource cleanup edit.
None
> Segment insertion angle complexity

- plantcv/plantcv/homology/acute.py
@HaleySchuhl caught bug working with homology tutorial
This is a bug fix
None
None
> fixed tutorial problem
